In [ ]:
import findspark
findspark.init()
from pyspark.sql import SparkSession

spark = SparkSession.builder \
        .master('local[*]') \
        .appName('Basics') \
        .config('spark.sql.ansi.enabled', 'false') \
        .getOrCreate()

print(spark.version)

ConnectionRefusedError: [Errno 61] Connection refused

In [2]:
import matplotlib
matplotlib.use("Agg")
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler, OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, ConfusionMatrixDisplay, classification_report
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from catboost import CatBoostClassifier, CatBoostRegressor

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# Assign home directory dynamically from notebook location
home_dir = os.path.dirname(os.getcwd())  # goes up from notebooks/ to project root

In [3]:
# Define functions
# Import additional packages
import datetime
import csv
import yaml
import io
import dill as pickle
import os

def get_datetime():
    """Returns datetime for filename use.

    :return: datetime
    :rtype: string
    """
    stamp = datetime.datetime.now()
    datetime_name = f"{stamp.year:04}{stamp.month:02}{stamp.day:02}_{stamp.hour:02}{stamp.minute:02}"
    print(datetime_name)
    return datetime_name

print('Functions ready!')

Functions ready!

In [4]:
import kagglehub

# Download latest dataset
path = kagglehub.dataset_download("nadyinky/sephora-products-and-skincare-reviews")

print("Path to dataset files:", path)

Path to dataset files: /Users/gyalm/.cache/kagglehub/datasets/nadyinky/sephora-products-and-skincare-reviews/versions/2

In [5]:
import glob

# Ensure data directories exist
os.makedirs(f"{home_dir}/data/raw", exist_ok=True)
os.makedirs(f"{home_dir}/data/cleaned", exist_ok=True)

# Capture a single timestamp for this data run
data_dt = get_datetime()
print(f"Data run timestamp: {data_dt}")

# path variable comes from cell-3 (kagglehub download)
csv_files = glob.glob(os.path.join(path, "*.csv"))

print("CSV Files Found:")
for file in csv_files:
    print("-", os.path.basename(file))

# Read each CSV suppressing mixed-type warnings
dfs = {os.path.basename(file): pd.read_csv(file, low_memory=False) for file in csv_files}

# Separate into individual DataFrames
product_df    = dfs.get("product_info.csv")
reviews_1_df  = dfs.get("reviews_0-250.csv")
reviews_2_df  = dfs.get("reviews_250-500.csv")
reviews_3_df  = dfs.get("reviews_500-750.csv")
reviews_4_df  = dfs.get("reviews_750-1250.csv")
reviews_5_df  = dfs.get("reviews_1250-end.csv")

# ── Save raw copies to data/raw/ with btl naming convention ──
product_df.to_csv(f"{home_dir}/data/raw/btl_raw_{data_dt}_product_info.csv",     index=False)
reviews_1_df.to_csv(f"{home_dir}/data/raw/btl_raw_{data_dt}_reviews_0-250.csv",   index=False)
reviews_2_df.to_csv(f"{home_dir}/data/raw/btl_raw_{data_dt}_reviews_250-500.csv", index=False)
reviews_3_df.to_csv(f"{home_dir}/data/raw/btl_raw_{data_dt}_reviews_500-750.csv", index=False)
reviews_4_df.to_csv(f"{home_dir}/data/raw/btl_raw_{data_dt}_reviews_750-1250.csv",index=False)
reviews_5_df.to_csv(f"{home_dir}/data/raw/btl_raw_{data_dt}_reviews_1250-end.csv",index=False)
print(f"Raw data saved to data/raw/ as btl_raw_{data_dt}_*.csv")

20260419_1201
Data run timestamp: 20260419_1201
CSV Files Found:
- product_info.csv
- reviews_0-250.csv
- reviews_1250-end.csv
- reviews_750-1250.csv
- reviews_250-500.csv
- reviews_500-750.csv

Raw data saved to data/raw/ as btl_raw_20260419_1201_*.csv

## Data Cleaning

The following cells document data preparation and cleaning steps performed on the raw Kaggle dataset.

In [6]:
# ── NULL CHECK: product_df ──────────────────────────────────────
print(f"product_df shape (raw): {product_df.shape}")
print()
print("Null counts per column:")
print(product_df.isnull().sum().to_string())

product_df shape (raw): (8494, 27)

Null counts per column:
product_id               0
product_name             0
brand_id                 0
brand_name               0
loves_count              0
rating                 278
reviews                278
size                  1631
variation_type        1444
variation_value       1598
variation_desc        7244
ingredients            945
price_usd                0
value_price_usd       8043
sale_price_usd        8224
limited_edition          0
new                      0
online_only              0
out_of_stock             0
sephora_exclusive        0
highlights            2207
primary_category         0
secondary_category       8
tertiary_category      990
child_count              0
child_max_price       5740
child_min_price       5740

In [7]:
# ── NULL CHECK: reviews (reviews_1_df as representative sample) ─────
print(f"reviews_1_df shape (raw): {reviews_1_df.shape}")
print()
print("Null counts per column:")
print(reviews_1_df.isnull().sum().to_string())

reviews_1_df shape (raw): (602130, 19)

Null counts per column:
Unnamed: 0                       0
author_id                        0
rating                           0
is_recommended              117486
helpfulness                 331832
total_feedback_count             0
total_neg_feedback_count         0
total_pos_feedback_count         0
submission_time                  0
review_text                    999
review_title                167011
skin_tone                   106056
eye_color                   138488
skin_type                    74683
hair_color                  141081
product_id                       0
product_name                     0
brand_name                       0
price_usd                        0

In [8]:
# ── DUPLICATE CHECK ─────────────────────────────────────────────────
dup_products = product_df.duplicated(subset=["product_id"]).sum()
print(f"product_df — duplicate product_id rows: {dup_products}")

for i, df in enumerate([reviews_1_df, reviews_2_df, reviews_3_df, reviews_4_df, reviews_5_df], 1):
    dup = df.duplicated(subset=["author_id", "product_id", "submission_time"]).sum()
    print(f"reviews_{i}_df — duplicate (author_id, product_id, submission_time) rows: {dup}")

product_df — duplicate product_id rows: 0
reviews_1_df — duplicate (author_id, product_id, submission_time) rows: 551
reviews_2_df — duplicate (author_id, product_id, submission_time) rows: 312
reviews_3_df — duplicate (author_id, product_id, submission_time) rows: 124
reviews_4_df — duplicate (author_id, product_id, submission_time) rows: 44
reviews_5_df — duplicate (author_id, product_id, submission_time) rows: 9

In [9]:
# ── BEFORE CLEANING: sample preview ─────────────────────────────────
print("=== product_df — before cleaning (key columns) ===")
display(product_df[["product_id", "product_name", "size", "ingredients", "price_usd"]].head(3))

print("\n=== reviews_1_df — before cleaning ===")
display(reviews_1_df[["author_id", "product_id", "submission_time", "rating", "is_recommended", "price_usd"]].head(3))

=== product_df — before cleaning (key columns) ===

,product_id,product_name,size,ingredients,price_usd
0,P473671,Fragrance Discovery Set,NaN,"['Capri Eau de Parfum:', 'Alcohol Denat. (SD A...",35.0
1,P473668,La Habana Eau de Parfum,3.4 oz/ 100 mL,"['Alcohol Denat. (SD Alcohol 39C), Parfum (Fra...",195.0
2,P473662,Rainbow Bar Eau de Parfum,3.4 oz/ 100 mL,"['Alcohol Denat. (SD Alcohol 39C), Parfum (Fra...",195.0

=== reviews_1_df — before cleaning ===

     author_id product_id submission_time  rating  is_recommended  price_usd
0   1741593524    P504322      2023-02-01       5             1.0       19.0
1  31423088263    P420652      2023-03-21       1             0.0       24.0
2   5061282401    P420652      2023-03-21       5             1.0       24.0

In [10]:
# ── CLEAN: product_df ───────────────────────────────────────────────
product_df_clean = product_df.copy()

before = len(product_df_clean)

# 1. Drop rows missing product_id or ingredients (required for concentration scoring)
product_df_clean = product_df_clean.dropna(subset=["product_id", "ingredients"])

# 2. Deduplicate on product_id (keep first occurrence)
product_df_clean = product_df_clean.drop_duplicates(subset=["product_id"], keep="first")

# 3. Coerce numeric types
for col in ["price_usd", "value_price_usd", "sale_price_usd", "rating", "loves_count", "reviews"]:
    product_df_clean[col] = pd.to_numeric(product_df_clean[col], errors="coerce")

# 4. Strip leading/trailing whitespace from string columns
for col in ["product_id", "product_name", "brand_name", "size", "ingredients"]:
    product_df_clean[col] = product_df_clean[col].astype(str).str.strip()

after = len(product_df_clean)
print(f"product_df: {before} rows -> {after} rows  (dropped {before - after} rows)")

product_df: 8494 rows -> 7549 rows  (dropped 945 rows)

In [11]:
# ── CLEAN: all reviews DataFrames ───────────────────────────────────
def clean_reviews(df):
    df = df.copy()
    before = len(df)

    # 1. Drop rows missing key identifiers or price/time
    df = df.dropna(subset=["author_id", "product_id", "price_usd", "submission_time"])

    # 2. Deduplicate on the natural composite key
    df = df.drop_duplicates(subset=["author_id", "product_id", "submission_time"], keep="first")

    # 3. Parse submission_time as datetime; drop rows that fail
    df["submission_time"] = pd.to_datetime(df["submission_time"], errors="coerce")
    df = df.dropna(subset=["submission_time"])

    # 4. Coerce numeric types (resolves mixed-type DtypeWarning)
    for col in ["rating", "price_usd", "helpfulness",
                "total_feedback_count", "total_neg_feedback_count", "total_pos_feedback_count"]:
        df[col] = pd.to_numeric(df[col], errors="coerce")
    df["is_recommended"] = pd.to_numeric(df["is_recommended"], errors="coerce")

    # 5. Strip string columns
    for col in ["author_id", "product_id", "product_name", "brand_name"]:
        df[col] = df[col].astype(str).str.strip()

    after = len(df)
    return df, before, after

review_frames = [reviews_1_df, reviews_2_df, reviews_3_df, reviews_4_df, reviews_5_df]
review_names  = ["reviews_0-250", "reviews_250-500", "reviews_500-750",
                 "reviews_750-1250", "reviews_1250-end"]

reviews_1_clean, b1, a1 = clean_reviews(reviews_1_df)
reviews_2_clean, b2, a2 = clean_reviews(reviews_2_df)
reviews_3_clean, b3, a3 = clean_reviews(reviews_3_df)
reviews_4_clean, b4, a4 = clean_reviews(reviews_4_df)
reviews_5_clean, b5, a5 = clean_reviews(reviews_5_df)

for name, b, a in zip(review_names,
                       [b1,b2,b3,b4,b5],
                       [a1,a2,a3,a4,a5]):
    print(f"{name}: {b:,} rows -> {a:,} rows  (dropped {b-a:,} rows)")

total_before = sum([b1,b2,b3,b4,b5])
total_after  = sum([a1,a2,a3,a4,a5])
print(f"\nTotal reviews: {total_before:,} -> {total_after:,}  (dropped {total_before-total_after:,} rows)")

reviews_0-250: 602,130 rows -> 601,579 rows  (dropped 551 rows)
reviews_250-500: 206,725 rows -> 206,413 rows  (dropped 312 rows)
reviews_500-750: 116,262 rows -> 116,138 rows  (dropped 124 rows)
reviews_750-1250: 119,317 rows -> 119,273 rows  (dropped 44 rows)
reviews_1250-end: 49,977 rows -> 49,968 rows  (dropped 9 rows)

Total reviews: 1,094,411 -> 1,093,371  (dropped 1,040 rows)

In [12]:
# ── AFTER CLEANING: sample preview ──────────────────────────────────
print("=== product_df_clean — after cleaning (key columns) ===")
display(product_df_clean[["product_id", "product_name", "size", "ingredients", "price_usd"]].head(3))

print("\n=== reviews_1_clean — after cleaning ===")
display(reviews_1_clean[["author_id", "product_id", "submission_time", "rating", "is_recommended", "price_usd"]].head(3))

print("\n=== Null counts after cleaning: product_df_clean ===")
print(product_df_clean[["product_id","product_name","size","ingredients","price_usd"]].isnull().sum().to_string())

print("\n=== Null counts after cleaning: reviews_1_clean ===")
print(reviews_1_clean[["author_id","product_id","submission_time","rating","price_usd"]].isnull().sum().to_string())

=== product_df_clean — after cleaning (key columns) ===

,product_id,product_name,size,ingredients,price_usd
0,P473671,Fragrance Discovery Set,NaN,"['Capri Eau de Parfum:', 'Alcohol Denat. (SD A...",35.0
1,P473668,La Habana Eau de Parfum,3.4 oz/ 100 mL,"['Alcohol Denat. (SD Alcohol 39C), Parfum (Fra...",195.0
2,P473662,Rainbow Bar Eau de Parfum,3.4 oz/ 100 mL,"['Alcohol Denat. (SD Alcohol 39C), Parfum (Fra...",195.0

=== reviews_1_clean — after cleaning ===

     author_id product_id submission_time  rating  is_recommended  price_usd
0   1741593524    P504322      2023-02-01       5             1.0       19.0
1  31423088263    P420652      2023-03-21       1             0.0       24.0
2   5061282401    P420652      2023-03-21       5             1.0       24.0

=== Null counts after cleaning: product_df_clean ===
product_id        0
product_name      0
size            999
ingredients       0
price_usd         0

=== Null counts after cleaning: reviews_1_clean ===
author_id          0
product_id         0
submission_time    0
rating             0
price_usd          0

## Data Warehouse Design — Star Schema ERD

The star schema below models the analytical data warehouse used to measure skincare product performance, seasonal purchase behavior, and ingredient-based recommendation scoring.

```mermaid
erDiagram
    FACT_PURCHASES {
        INT purchase_sk PK
        STRING product_sk FK
        STRING author_sk FK
        INT time_sk FK
        STRING brand_sk FK
        FLOAT price_usd
        FLOAT rating
        FLOAT total_concentration
        INT target
        BOOLEAN is_recommended
        INT total_feedback_count
        INT total_pos_feedback_count
        INT total_neg_feedback_count
        FLOAT helpfulness
    }

    DIM_PRODUCT {
        STRING product_sk PK
        STRING product_id NK
        STRING product_name
        STRING primary_category
        STRING secondary_category
        STRING tertiary_category
        FLOAT price_usd
        INT loves_count
        FLOAT size_oz
        FLOAT size_mL
        TEXT ingredients
        BOOLEAN limited_edition
        BOOLEAN new_product
        BOOLEAN online_only
        BOOLEAN out_of_stock
        BOOLEAN sephora_exclusive
    }

    DIM_CUSTOMER {
        STRING author_sk PK
        STRING author_id NK
        STRING skin_tone
        STRING eye_color
        STRING skin_type
        STRING hair_color
    }

    DIM_TIME {
        INT time_sk PK
        DATETIME submission_time NK
        INT year
        INT month
        INT quarter
        STRING season
        BOOLEAN is_cold_month
    }

    DIM_BRAND {
        STRING brand_sk PK
        STRING brand_id NK
        STRING brand_name
    }

    DIM_PRODUCT ||--o{ FACT_PURCHASES : "has"
    DIM_CUSTOMER ||--o{ FACT_PURCHASES : "makes"
    DIM_TIME ||--o{ FACT_PURCHASES : "occurs at"
    DIM_BRAND ||--o{ FACT_PURCHASES : "belongs to"
```

In [13]:
# -- ENCODING & TRANSFORMATION: Boolean columns and season tagging --------

# product_df_clean: encode boolean columns to int (0/1)
bool_cols_product = ["limited_edition", "new", "online_only", "out_of_stock", "sephora_exclusive"]
for col in bool_cols_product:
    if col in product_df_clean.columns:
        product_df_clean[col] = product_df_clean[col].map(
            {True: 1, False: 0, "True": 1, "False": 0, 1: 1, 0: 0}
        ).fillna(0).astype(int)

print("product_df_clean — boolean encoding done")
print(product_df_clean[bool_cols_product].head(3))
print()

# reviews: add season and is_cold_month columns
def add_season(df):
    df = df.copy()
    df["submission_time"] = pd.to_datetime(df["submission_time"], errors="coerce")
    df["is_cold_month"] = df["submission_time"].dt.month.isin([1, 2, 3, 4]).astype(int)
    df["season"] = df["is_cold_month"].map({1: "Cold", 0: "Warm"})
    df["is_recommended"] = pd.to_numeric(df["is_recommended"], errors="coerce").fillna(0).astype(int)
    return df

reviews_1_clean = add_season(reviews_1_clean)
reviews_2_clean = add_season(reviews_2_clean)
reviews_3_clean = add_season(reviews_3_clean)
reviews_4_clean = add_season(reviews_4_clean)
reviews_5_clean = add_season(reviews_5_clean)

# Sample output
print("reviews_1_clean — season columns added")
print(reviews_1_clean[["author_id","product_id","submission_time","season","is_cold_month","is_recommended"]].head(3))
cold_total = sum(df["is_cold_month"].sum() for df in [reviews_1_clean,reviews_2_clean,reviews_3_clean,reviews_4_clean,reviews_5_clean])
warm_total = sum((1 - df["is_cold_month"]).sum() for df in [reviews_1_clean,reviews_2_clean,reviews_3_clean,reviews_4_clean,reviews_5_clean])
print(f"\nCold-month reviews (Jan-Apr): {cold_total:,}")
print(f"Warm-month reviews (May-Dec): {warm_total:,}")

product_df_clean — boolean encoding done
   limited_edition  new  online_only  out_of_stock  sephora_exclusive
0                0    0            1             0                  0
1                0    0            1             0                  0
2                0    0            1             0                  0

reviews_1_clean — season columns added
     author_id product_id submission_time season  is_cold_month  \
0   1741593524    P504322      2023-02-01   Cold              1
1  31423088263    P420652      2023-03-21   Cold              1
2   5061282401    P420652      2023-03-21   Cold              1

   is_recommended
0               1
1               0
2               1

Cold-month reviews (Jan-Apr): 434,237
Warm-month reviews (May-Dec): 659,134

In [14]:
# ── SAVE CLEANED DATA to data/cleaned/ with btl naming convention ──
product_df_clean.to_csv(f"{home_dir}/data/cleaned/btl_clean_{data_dt}_product_info.csv",     index=False)
reviews_1_clean.to_csv(f"{home_dir}/data/cleaned/btl_clean_{data_dt}_reviews_0-250.csv",     index=False)
reviews_2_clean.to_csv(f"{home_dir}/data/cleaned/btl_clean_{data_dt}_reviews_250-500.csv",   index=False)
reviews_3_clean.to_csv(f"{home_dir}/data/cleaned/btl_clean_{data_dt}_reviews_500-750.csv",   index=False)
reviews_4_clean.to_csv(f"{home_dir}/data/cleaned/btl_clean_{data_dt}_reviews_750-1250.csv",  index=False)
reviews_5_clean.to_csv(f"{home_dir}/data/cleaned/btl_clean_{data_dt}_reviews_1250-end.csv",  index=False)
print(f"Cleaned data saved to data/cleaned/ as btl_clean_{data_dt}_*.csv")

Cleaned data saved to data/cleaned/ as btl_clean_20260419_1201_*.csv

## Star Schema Construction — Dimension & Fact Tables

Builds the analytical star schema (Kimball dimensional model) directly from the cleaned DataFrames in memory.
Five tables are produced: `DIM_PRODUCT`, `DIM_BRAND`, `DIM_CUSTOMER`, `DIM_TIME`, and `FACT_PURCHASES`.

Key steps applied here beyond the base cleaning:
- Products without a parseable `size_oz` are dropped (required for ingredient concentration scoring)
- `total_concentration = Σ(standard_conc_percentage × size_oz)` over P442990's 44 known ingredients — computed per product
- Binary `target` label assigned at the median threshold: `1` if `total_concentration > 0.075`, else `0`
- Null `helpfulness` in fact rows filled with `0.0` (undefined when `total_feedback_count = 0`, not erroneous)
- Optional customer demographics (`skin_tone`, `eye_color`, `skin_type`, `hair_color`) retain nulls — customers made valid purchases without completing their profile
- `secondary_category` and `tertiary_category` in DIM_PRODUCT retain nulls — not all products carry a full category hierarchy
- `size_mL` retains nulls for products listed in oz-only format — `size_oz` is sufficient for concentration scoring

In [ ]:
# ── STAR SCHEMA CONSTRUCTION — Dimension & Fact Tables ──────────────────
import re

# Ingredient concentration lookup (P442990 formulation, 44 ingredients)
INGREDIENT_CONC = {
    'Aqua (Water)': 0.65, 'Zinc Oxide': 0.15,
    'Caprylic/Capric Triglyceride': 0.06, 'Aloe Barbadensis Leaf Juice': 0.03,
    'Glycerin': 0.06, 'Caprylyl Caprylate/Caprate': 0.02,
    'Propanediol': 0.03, 'Arachidyl Alcohol': 0.0175,
    'Cetearyl Alcohol': 0.035, 'Coco-Glucoside': 0.015,
    'Oryza Sativa Starch': 0.015, 'Pongamia Glabra Seed Oil': 0.02,
    'Microcrystalline Cellulose': 0.0175, 'Behenyl Alcohol': 0.03,
    'Phenoxyethanol': 0.0075, 'Arachidyl Glucoside': 0.0125,
    'Isostearic Acid': 0.0175, 'Lecithin': 0.0105,
    'Polyglyceryl-3 Polyricinoleate': 0.0125, 'Polyhydroxystearic Acid': 0.0175,
    'Passiflora Edulis Fruit Extract': 0.0105, 'Ethylhexylglycerin': 0.0065,
    'Glyceryl Oleate': 0.0125, 'Vaccinium Macrocarpon (Cranberry) Seed Oil': 0.0055,
    'Xanthan Gum': 0.0055, 'Cellulose Gum': 0.0055,
    'Sodium Chloride': 0.0105, 'Hippophae Rhamnoides Oil': 0.0055,
    'Citrus Nobilis (Mandarin Orange) Peel Oil': 0.0055,
    'Anthemis Nobilis Flower Oil': 0.0055,
    'Cinnamomum Camphora Linalloliferum (Ho Wood) Leaf Oil': 0.0055,
    'Pelargonium Graveolens Flower Oil': 0.0055, 'Glucose': 0.0055,
    'Parfum* (Fragrance)': 0.0055, 'Helianthus Annuus (Sunflower) Seed Oil': 0.0125,
    'Tocopherol': 0.0055, 'Rosmarinus Officinalis (Rosmary) Leaf Extract': 0.0055,
    'Hydrogenated Palm Glycerides Citrate': 0.0055, 'Citric Acid': 0.0055,
    'Sodium Hydroxide': 0.0055, 'Citronellol': 0.00255,
    'Geraniol': 0.00255, 'Limonene': 0.00255, 'Linalool': 0.00255,
}
CONC_THRESHOLD = 0.075  # median threshold from Spark SQL (cell 356ccd2b)

def _parse_oz(s):
    m = re.search(r'(\d+(?:\.\d+)?)\s*oz', str(s), re.IGNORECASE)
    try: return float(m.group(1)) if m else None
    except: return None

def _parse_ml(s):
    m = re.search(r'(\d+(?:\.\d+)?)\s*mL', str(s))
    try: return float(m.group(1)) if m else None
    except: return None

# Union all cleaned review DataFrames
all_reviews = pd.concat(
    [reviews_1_clean.copy(), reviews_2_clean.copy(), reviews_3_clean.copy(),
     reviews_4_clean.copy(), reviews_5_clean.copy()], ignore_index=True
)
all_reviews['submission_time'] = pd.to_datetime(all_reviews['submission_time'], errors='coerce')
all_reviews = all_reviews.dropna(subset=['submission_time'])
all_reviews['submission_date'] = all_reviews['submission_time'].dt.date

# ── DIM_PRODUCT ──────────────────────────────────────────────────────────
dp = product_df_clean.copy()
dp['size_oz'] = dp['size'].apply(_parse_oz)
dp['size_mL'] = dp['size'].apply(_parse_ml)
dp = dp[dp['size_oz'].notna() & (dp['size_oz'] > 0)]
dp = dp[dp['price_usd'].notna() & (dp['price_usd'] > 0)]
for _col in ['product_name', 'brand_name', 'ingredients']:
    dp = dp[dp[_col].notna() & ~dp[_col].isin(['nan', 'None', ''])]
dp['total_concentration'] = dp.apply(
    lambda r: sum(INGREDIENT_CONC.get(ing.strip(), 0) * r['size_oz']
                  for ing in str(r['ingredients']).split(', ')), axis=1)
dp['target'] = (dp['total_concentration'] > CONC_THRESHOLD).astype(int)
dim_product = dp[[
    'product_id', 'product_name', 'primary_category', 'secondary_category',
    'tertiary_category', 'price_usd', 'loves_count', 'size_oz', 'size_mL',
    'ingredients', 'limited_edition', 'new', 'online_only', 'out_of_stock',
    'sephora_exclusive', 'total_concentration', 'target',
]].rename(columns={'new': 'new_product'})

# product → brand lookup (kept outside dim for fact join)
_prod_brand = product_df_clean[['product_id', 'brand_id']].dropna(subset=['brand_id'])

# ── DIM_BRAND ─────────────────────────────────────────────────────────────
dim_brand = (
    product_df_clean[['brand_id', 'brand_name']]
    .dropna(subset=['brand_id', 'brand_name'])
    .pipe(lambda d: d[d['brand_name'].str.strip() != ''])
    .drop_duplicates(subset=['brand_id'], keep='first')
    .reset_index(drop=True)
)

# ── DIM_CUSTOMER ──────────────────────────────────────────────────────────
dc = all_reviews[['author_id', 'skin_tone', 'eye_color', 'skin_type', 'hair_color']].copy()
dc = dc[dc['author_id'].notna() & ~dc['author_id'].isin(['nan', 'None', ''])]
for _col in ['skin_tone', 'eye_color', 'skin_type', 'hair_color']:
    dc[_col] = dc[_col].replace(['nan', 'None', ''], pd.NA)
dim_customer = dc.drop_duplicates(subset=['author_id'], keep='first').reset_index(drop=True)

# ── DIM_TIME ──────────────────────────────────────────────────────────────
_dates = pd.to_datetime(
    pd.Series(all_reviews['submission_date'].unique())
).sort_values().reset_index(drop=True)
dim_time = pd.DataFrame({
    'time_sk':       range(len(_dates)),
    'submission_date': _dates,
    'year':          _dates.dt.year,
    'month':         _dates.dt.month,
    'quarter':       _dates.dt.quarter,
    'is_cold_month': _dates.dt.month.isin([1,2,3,4]).astype(int),
    'season':        _dates.dt.month.isin([1,2,3,4]).map({True:'Cold', False:'Warm'}),
})

# ── FACT_PURCHASES ────────────────────────────────────────────────────────
fact = all_reviews[[
    'author_id', 'product_id', 'submission_date', 'price_usd', 'rating',
    'is_recommended', 'total_feedback_count', 'total_pos_feedback_count',
    'total_neg_feedback_count', 'helpfulness',
]].copy()
fact['helpfulness'] = pd.to_numeric(fact['helpfulness'], errors='coerce').fillna(0.0)
fact = fact[fact['price_usd'].notna() & (fact['price_usd'] > 0)]
fact = fact[fact['rating'].notna() & fact['rating'].between(1, 5)]
fact = fact.merge(dim_product[['product_id', 'total_concentration', 'target']], on='product_id', how='inner')
fact = fact.merge(_prod_brand, on='product_id', how='inner')
fact = fact[fact['brand_id'].isin(dim_brand['brand_id'].values)]
fact = fact[fact['author_id'].isin(dim_customer['author_id'].values)]
_dt_lookup = dim_time[['time_sk', 'submission_date']].copy()
_dt_lookup['submission_date'] = pd.to_datetime(_dt_lookup['submission_date']).dt.date
fact = fact.merge(_dt_lookup, on='submission_date', how='inner')
fact = fact.reset_index(drop=True)
fact.insert(0, 'purchase_sk', range(1, len(fact) + 1))
fact = fact.rename(columns={'product_id': 'product_sk', 'author_id': 'author_sk', 'brand_id': 'brand_sk'})
fact_purchases = fact[[
    'purchase_sk', 'product_sk', 'author_sk', 'time_sk', 'brand_sk',
    'price_usd', 'rating', 'total_concentration', 'target',
    'is_recommended', 'total_feedback_count', 'total_pos_feedback_count',
    'total_neg_feedback_count', 'helpfulness',
]]

# ── SAVE to data/cleaned/ ─────────────────────────────────────────────────
dim_product.to_csv(    f"{home_dir}/data/cleaned/btl_clean_{data_dt}_dim_product.csv",    index=False)
dim_brand.to_csv(      f"{home_dir}/data/cleaned/btl_clean_{data_dt}_dim_brand.csv",      index=False)
dim_customer.to_csv(   f"{home_dir}/data/cleaned/btl_clean_{data_dt}_dim_customer.csv",   index=False)
dim_time.to_csv(       f"{home_dir}/data/cleaned/btl_clean_{data_dt}_dim_time.csv",       index=False)
fact_purchases.to_csv( f"{home_dir}/data/cleaned/btl_clean_{data_dt}_fact_purchases.csv", index=False)

for _name, _df in [('DIM_PRODUCT', dim_product), ('DIM_BRAND', dim_brand),
                   ('DIM_CUSTOMER', dim_customer), ('DIM_TIME', dim_time),
                   ('FACT_PURCHASES', fact_purchases)]:
    print(f"{_name}: {len(_df):,} rows x {len(_df.columns)} cols")
print(f"Star schema tables saved to data/cleaned/ as btl_clean_{data_dt}_*.csv")

In [15]:
product_df = spark.read.csv(f"{home_dir}/data/cleaned/btl_clean_{data_dt}_product_info.csv", inferSchema=True, header=True)
product_df.show(10)
product_df.createOrReplaceTempView("product_df")

26/04/19 12:02:02 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

+----------+--------------------+--------+----------+-----------+------+-------+---------------+--------------------+--------------------+--------------+--------------------+---------+---------------+--------------+---------------+---+-----------+------------+-----------------+--------------------+----------------+------------------+--------------------+-----------+---------------+---------------+
|product_id|        product_name|brand_id|brand_name|loves_count|rating|reviews|           size|      variation_type|     variation_value|variation_desc|         ingredients|price_usd|value_price_usd|sale_price_usd|limited_edition|new|online_only|out_of_stock|sephora_exclusive|          highlights|primary_category|secondary_category|   tertiary_category|child_count|child_max_price|child_min_price|
+----------+--------------------+--------+----------+-----------+------+-------+---------------+--------------------+--------------------+--------------+--------------------+---------+---------------+--------------+---------------+---+-----------+------------+-----------------+--------------------+----------------+------------------+--------------------+-----------+---------------+---------------+
|   P473671|Fragrance Discove...|    6342|     19-69|       6320|3.6364|   11.0|           NULL|                NULL|                NULL|          NULL|['Capri Eau de Pa...|     35.0|           NULL|          NULL|              0|  0|          1|           0|                0|['Unisex/ Genderl...|       Fragrance| Value & Gift Sets|   Perfume Gift Sets|          0|           NULL|           NULL|
|   P473668|La Habana Eau de ...|    6342|     19-69|       3827|4.1538|   13.0| 3.4 oz/ 100 mL|Size + Concentrat...|      3.4 oz/ 100 mL|          NULL|['Alcohol Denat. ...|    195.0|           NULL|          NULL|              0|  0|          1|           0|                0|['Unisex/ Genderl...|       Fragrance|             Women|             Perfume|          2|           85.0|           30.0|
|   P473662|Rainbow Bar Eau d...|    6342|     19-69|       3253|  4.25|   16.0| 3.4 oz/ 100 mL|Size + Concentrat...|      3.4 oz/ 100 mL|          NULL|['Alcohol Denat. ...|    195.0|           NULL|          NULL|              0|  0|          1|           0|                0|['Unisex/ Genderl...|       Fragrance|             Women|             Perfume|          2|           75.0|           30.0|
|   P473660|Kasbah Eau de Parfum|    6342|     19-69|       3018|4.4762|   21.0| 3.4 oz/ 100 mL|Size + Concentrat...|      3.4 oz/ 100 mL|          NULL|['Alcohol Denat. ...|    195.0|           NULL|          NULL|              0|  0|          1|           0|                0|['Unisex/ Genderl...|       Fragrance|             Women|             Perfume|          2|           75.0|           30.0|
|   P473658|Purple Haze Eau d...|    6342|     19-69|       2691|3.2308|   13.0| 3.4 oz/ 100 mL|Size + Concentrat...|      3.4 oz/ 100 mL|          NULL|['Alcohol Denat. ...|    195.0|           NULL|          NULL|              0|  0|          1|           0|                0|['Unisex/ Genderl...|       Fragrance|             Women|             Perfume|          2|           75.0|           30.0|
|   P473661|Kasbah Eau de Par...|    6342|     19-69|       2448|4.4762|   21.0|0.25 oz/ 7.5 mL|Size + Concentrat...|0.25 oz/ 7.5 mL E...|          NULL|['Alcohol Denat. ...|     30.0|           NULL|          NULL|              0|  0|          1|           0|                0|['Warm &Spicy Sce...|       Fragrance|             Women|Rollerballs & Tra...|          0|           NULL|           NULL|
|   P473659|Purple Haze Eau d...|    6342|     19-69|       1619|3.2308|   13.0|0.25 oz/ 7.5 mL|Size + Concentrat...|     0.25 oz/ 7.5 mL|          NULL|['Alcohol Denat. ...|     30.0|           NULL|          NULL|              0|  0|          1|           0|                0|['Unisex/ Genderl...|       Fragrance|             Women|Rollerballs & Tra...|          0|           NULL|           NULL|
|   P473666|Invisible Post Ea...|    6342|     19-69|       1542| 3.625|    8.0| 3.4 oz/ 100 mL|Size + Concentrat...|      3.4 oz/ 100 mL|          NULL|['Alcohol Denat. ...|    195.0|           NULL|          NULL|              0|  0|          1|           0|                0|['Unisex/ Genderl...|       Fragrance|             Women|             Perfume|          2|           75.0|           30.0|
|   P472300| Capri Eau de Parfum|    6342|     19-69|       1542|3.5714|    7.0| 3.4 oz/ 100 mL|Size + Concentrat...|3.4 oz/ 100 mL Ea...|          NULL|['Alcohol Denat. ...|    195.0|           NULL|          NULL|              0|  0|          1|           0|                0|['Fresh Scent', '...|       Fragrance|             Women|             Perfume|          2|           75.0|           30.0|
|   P473667|Invisible Post Ea...|    6342|     19-69|       1377| 3.625|    8.0|0.25 oz/ 7.5 mL|Size + Concentrat...|     0.25 oz/ 7.5 mL|          NULL|['Alcohol Denat. ...|     30.0|           NULL|          NULL|              0|  0|          1|           0|                0|['Unisex/ Genderl...|       Fragrance|             Women|Rollerballs & Tra...|          0|           NULL|           NULL|
+----------+--------------------+--------+----------+-----------+------+-------+---------------+--------------------+--------------------+--------------+--------------------+---------+---------------+--------------+---------------+---+-----------+------------+-----------------+--------------------+----------------+------------------+--------------------+-----------+---------------+---------------+
only showing top 10 rows

In [16]:
reviews_1_df = spark.read.csv(f"{home_dir}/data/cleaned/btl_clean_{data_dt}_reviews_0-250.csv",   inferSchema=True, header=True)
reviews_1_df.show(10)
reviews_1_df.createOrReplaceTempView("reviews_1_df")

reviews_2_df = spark.read.csv(f"{home_dir}/data/cleaned/btl_clean_{data_dt}_reviews_250-500.csv", inferSchema=True, header=True)
reviews_2_df.show(10)
reviews_2_df.createOrReplaceTempView("reviews_2_df")

reviews_3_df = spark.read.csv(f"{home_dir}/data/cleaned/btl_clean_{data_dt}_reviews_500-750.csv", inferSchema=True, header=True)
reviews_3_df.show(10)
reviews_3_df.createOrReplaceTempView("reviews_3_df")

reviews_4_df = spark.read.csv(f"{home_dir}/data/cleaned/btl_clean_{data_dt}_reviews_750-1250.csv",inferSchema=True, header=True)
reviews_4_df.show(10)
reviews_4_df.createOrReplaceTempView("reviews_4_df")

reviews_5_df = spark.read.csv(f"{home_dir}/data/cleaned/btl_clean_{data_dt}_reviews_1250-end.csv",inferSchema=True, header=True)
reviews_5_df.show(10)
reviews_5_df.createOrReplaceTempView("reviews_5_df")

[Stage 4:=============================>                            (6 + 6) / 12]

+----------+-----------+------+--------------+-----------+--------------------+------------------------+------------------------+---------------+--------------------+--------------------+-----------+---------+-----------+----------+----------+--------------------+----------+---------+-------------+------+
|Unnamed: 0|  author_id|rating|is_recommended|helpfulness|total_feedback_count|total_neg_feedback_count|total_pos_feedback_count|submission_time|         review_text|        review_title|  skin_tone|eye_color|  skin_type|hair_color|product_id|        product_name|brand_name|price_usd|is_cold_month|season|
+----------+-----------+------+--------------+-----------+--------------------+------------------------+------------------------+---------------+--------------------+--------------------+-----------+---------+-----------+----------+----------+--------------------+----------+---------+-------------+------+
|         0| 1741593524|     5|             1|        1.0|                   2|                       0|                       2|     2023-02-01|I use this with t...|Taught me how to ...|       NULL|    brown|        dry|     black|   P504322|Gentle Hydra-Gel ...|  NUDESTIX|     19.0|            1|  Cold|
|         1|31423088263|     1|             0|       NULL|                   0|                       0|                       0|     2023-03-21|I bought this lip...|        Disappointed|       NULL|     NULL|       NULL|      NULL|   P420652|Lip Sleeping Mask...|   LANEIGE|     24.0|            1|  Cold|
|         2| 5061282401|     5|             1|       NULL|                   0|                       0|                       0|     2023-03-21|My review title s...|New Favorite Routine|      light|    brown|        dry|    blonde|   P420652|Lip Sleeping Mask...|   LANEIGE|     24.0|            1|  Cold|
|         3| 6083038851|     5|             1|       NULL|                   0|                       0|                       0|     2023-03-20|I’ve always loved...|Can't go wrong wi...|       NULL|    brown|combination|     black|   P420652|Lip Sleeping Mask...|   LANEIGE|     24.0|            1|  Cold|
|         4|47056667835|     5|             1|       NULL|                   0|                       0|                       0|     2023-03-20|If you have dry c...|     A must have !!!|      light|    hazel|combination|      NULL|   P420652|Lip Sleeping Mask...|   LANEIGE|     24.0|            1|  Cold|
|         5|42802569154|     4|             1|        1.0|                   1|                       0|                       1|     2023-03-19|The scent isn’t m...|              Great!|lightMedium|    brown|     normal|     brown|   P420652|Lip Sleeping Mask...|   LANEIGE|     24.0|            1|  Cold|
|         6| 6941883808|     2|             0|       0.25|                   8|                       6|                       2|     2023-03-19|I’ll give this 2 ...|Dried my lips out...|      light|     blue|combination|     brown|   P420652|Lip Sleeping Mask...|   LANEIGE|     24.0|            1|  Cold|
|         7|27926227988|     5|             1|       NULL|                   0|                       0|                       0|     2023-03-19|I use this at nig...|         Works great|  fairLight|    brown|combination|     brown|   P420652|Lip Sleeping Mask...|   LANEIGE|     24.0|            1|  Cold|
|         8| 7656791726|     5|             1|        1.0|                   1|                       0|                       1|     2023-03-18|I love this stuff...|          Must have.|      light|     blue|     normal|    blonde|   P420652|Lip Sleeping Mask...|   LANEIGE|     24.0|            1|  Cold|
|         9|38727834382|     5|             1|        1.0|                   2|                       0|                       2|     2023-03-18|I purchased the S...|     RUN TO PURCHASE|      light|    brown|     normal|     brown|   P420652|Lip Sleeping Mask...|   LANEIGE|     24.0|            1|  Cold|
+----------+-----------+------+--------------+-----------+--------------------+------------------------+------------------------+---------------+--------------------+--------------------+-----------+---------+-----------+----------+----------+--------------------+----------+---------+-------------+------+
only showing top 10 rows

+----------+-----------+------+--------------+------------------+--------------------+------------------------+------------------------+---------------+--------------------+--------------------+-----------+---------+-----------+----------+----------+--------------------+--------------+---------+-------------+------+
|Unnamed: 0|  author_id|rating|is_recommended|       helpfulness|total_feedback_count|total_neg_feedback_count|total_pos_feedback_count|submission_time|         review_text|        review_title|  skin_tone|eye_color|  skin_type|hair_color|product_id|        product_name|    brand_name|price_usd|is_cold_month|season|
+----------+-----------+------+--------------+------------------+--------------------+------------------------+------------------------+---------------+--------------------+--------------------+-----------+---------+-----------+----------+----------+--------------------+--------------+---------+-------------+------+
|         0| 2190293206|     2|             0|              NULL|                   0|                       0|                       0|     2023-03-19|Used to swear by ...|                NULL|lightMedium|    brown|combination|     brown|   P443842|Retinol Anti-Agin...|The INKEY List|    12.99|            1|  Cold|
|         1| 9113341005|     5|             1|              NULL|                   0|                       0|                       0|     2023-03-18|I’ve only been us...|More tolerable th...|       deep|    brown|     normal|     black|   P443842|Retinol Anti-Agin...|The INKEY List|    12.99|            1|  Cold|
|         2|23866342710|     1|             0|               1.0|                  13|                       0|                      13|     2023-03-12|Why, why, why wou...|New formula is aw...|  fairLight|     blue|combination|    blonde|   P443842|Retinol Anti-Agin...|The INKEY List|    12.99|            1|  Cold|
|         3| 1328806527|     1|             0|0.9411759972572328|                  17|                       1|                      16|     2023-03-12|I have used this ...|Recently reformul...|      light|    brown|combination|      gray|   P443842|Retinol Anti-Agin...|The INKEY List|    12.99|            1|  Cold|
|         4|31262847082|     5|             1|               1.0|                   1|                       0|                       1|     2023-03-09|Great product for...|Must have product...|lightMedium|    hazel|combination|     brown|   P443842|Retinol Anti-Agin...|The INKEY List|    12.99|            1|  Cold|
|         5|38092205147|     4|             1|               1.0|                   5|                       0|                       5|     2023-03-06|I’ve been using t...|                NULL|       NULL|     NULL|       NULL|      NULL|   P443842|Retinol Anti-Agin...|The INKEY List|    12.99|            1|  Cold|
|         6| 5090375964|     4|             1|               1.0|                   1|                       0|                       1|     2023-03-05|Decent serum ; it...|          Great size|       NULL|    brown|combination|     black|   P443842|Retinol Anti-Agin...|The INKEY List|    12.99|            1|  Cold|
|         7|42425576020|     5|             1|               1.0|                   2|                       0|                       2|     2023-03-05|I recently bought...|    No smell for me!|  fairLight|     gray|combination|    blonde|   P443842|Retinol Anti-Agin...|The INKEY List|    12.99|            1|  Cold|
|         8| 6768361454|     1|             0|0.9090909957885742|                  11|                       1|                      10|     2023-03-03|Been using this p...|                NULL|      light|    hazel|combination|     brown|   P443842|Retinol Anti-Agin...|The INKEY List|    12.99|            1|  Cold|
|         9| 6860968769|     1|             0| 0.800000011920929|                  15|                       3|                      12|     2023-03-01|I used to swear b...|Threw up in my mo...|lightMedium|     blue|        dry|     brown|   P443842|Retinol Anti-Agin...|The INKEY List|    12.99|            1|  Cold|
+----------+-----------+------+--------------+------------------+--------------------+------------------------+------------------------+---------------+--------------------+--------------------+-----------+---------+-----------+----------+----------+--------------------+--------------+---------+-------------+------+
only showing top 10 rows
+----------+-----------+------+--------------+-----------+--------------------+------------------------+------------------------+---------------+--------------------+--------------------+---------+---------+-----------+----------+----------+--------------------+----------+---------+-------------+------+
|Unnamed: 0|  author_id|rating|is_recommended|helpfulness|total_feedback_count|total_neg_feedback_count|total_pos_feedback_count|submission_time|         review_text|        review_title|skin_tone|eye_color|  skin_type|hair_color|product_id|        product_name|brand_name|price_usd|is_cold_month|season|
+----------+-----------+------+--------------+-----------+--------------------+------------------------+------------------------+---------------+--------------------+--------------------+---------+---------+-----------+----------+----------+--------------------+----------+---------+-------------+------+
|         0| 2079014373|     5|             1|       NULL|                   0|                       0|                       0|     2023-03-14|These are the onl...| Best Pimple Patches|   medium|     blue|     normal|      NULL|   P442857|Focuspot Micro Ti...| Dr. Jart+|     20.0|            1|  Cold|
|         1|12631885517|     4|             1|       NULL|                   0|                       0|                       0|     2023-02-08|One of my ingrown...|           It works!|mediumTan|    brown|combination|     black|   P442857|Focuspot Micro Ti...| Dr. Jart+|     20.0|            1|  Cold|
|         2| 2321761961|     5|             1|        1.0|                   1|                       0|                       1|     2023-02-05|I have tried 10 d...|Good for a large ...|     NULL|    hazel|combination|    blonde|   P442857|Focuspot Micro Ti...| Dr. Jart+|     20.0|            1|  Cold|
|         3| 1380382883|     4|             1|       NULL|                   0|                       0|                       0|     2023-01-24|Love these for my...|Micro tips are a ...|    light|    brown|combination|     black|   P442857|Focuspot Micro Ti...| Dr. Jart+|     20.0|            1|  Cold|
|         4| 8871759068|     4|             1|        1.0|                   1|                       0|                       1|     2023-01-15|Best so far - tho...|                NULL|     NULL|     NULL|       NULL|      NULL|   P442857|Focuspot Micro Ti...| Dr. Jart+|     20.0|            1|  Cold|
|         5| 1329183381|     1|             0|        1.0|                   3|                       0|                       3|     2022-12-19|Not worth it. The...|                NULL|     fair|     blue|     normal|    blonde|   P442857|Focuspot Micro Ti...| Dr. Jart+|     20.0|            0|  Warm|
|         6| 5552475859|     5|             1|        1.0|                   4|                       0|                       4|     2022-11-03|I purchased these...|Worth the money c...|    light|    green|       oily|    blonde|   P442857|Focuspot Micro Ti...| Dr. Jart+|     20.0|            0|  Warm|
|         7| 6152128389|     5|             1|        1.0|                   6|                       0|                       6|     2022-08-31|I will be the fir...|Not your momma's ...|    light|    brown|combination|     brown|   P442857|Focuspot Micro Ti...| Dr. Jart+|     20.0|            0|  Warm|
|         8| 1298593082|     5|             1|        1.0|                   3|                       0|                       3|     2022-08-20|Both my husband (...|Surprisingly effe...|    light|     blue|     normal|     brown|   P442857|Focuspot Micro Ti...| Dr. Jart+|     20.0|            0|  Warm|
|         9| 8664488720|     2|             0|        1.0|                   2|                       0|                       2|     2022-08-18|I wish I had read...|      Waste of Money|     fair|    brown|        dry|    blonde|   P442857|Focuspot Micro Ti...| Dr. Jart+|     20.0|            0|  Warm|
+----------+-----------+------+--------------+-----------+--------------------+------------------------+------------------------+---------------+--------------------+--------------------+---------+---------+-----------+----------+----------+--------------------+----------+---------+-------------+------+
only showing top 10 rows

+----------+-----------+------+--------------+------------------+--------------------+------------------------+------------------------+---------------+--------------------+--------------------+---------+---------+-----------+----------+----------+--------------------+----------+---------+-------------+------+
|Unnamed: 0|  author_id|rating|is_recommended|       helpfulness|total_feedback_count|total_neg_feedback_count|total_pos_feedback_count|submission_time|         review_text|        review_title|skin_tone|eye_color|  skin_type|hair_color|product_id|        product_name|brand_name|price_usd|is_cold_month|season|
+----------+-----------+------+--------------+------------------+--------------------+------------------------+------------------------+---------------+--------------------+--------------------+---------+---------+-----------+----------+----------+--------------------+----------+---------+-------------+------+
|         0| 8554483509|     2|             0|              NULL|                   0|                       0|                       0|     2023-03-21|This was gifted b...|Nice packaging bu...|    light|    brown|combination|      NULL|   P467976|(Re)setting 100% ...|Supergoop!|     35.0|            1|  Cold|
|         1|24710523057|     2|             0|               1.0|                   2|                       0|                       2|     2023-03-07|I didn’t like it;...|Packaging is not ...|     NULL|    brown|combination|      NULL|   P467976|(Re)setting 100% ...|Supergoop!|     35.0|            1|  Cold|
|         2| 8429283179|     5|             1|0.9411759972572328|                  34|                       2|                      32|     2023-03-01|Y’all….I’m beggin...|   PLS READ THIS LOL|    light|    green|     normal|     brown|   P467976|(Re)setting 100% ...|Supergoop!|     35.0|            1|  Cold|
|         3| 8105185455|     1|             0|               0.0|                   5|                       5|                       0|     2023-02-27|I have not figure...|           At a loss|      tan|    brown|combination|     black|   P467976|(Re)setting 100% ...|Supergoop!|     35.0|            1|  Cold|
|         4| 1515931062|     1|             0|               0.0|                   7|                       7|                       0|     2023-02-27|I’m at a loss as ...|        NOT for me!!|     fair|     blue|combination|    blonde|   P467976|(Re)setting 100% ...|Supergoop!|     35.0|            1|  Cold|
|         5| 1477145203|     5|             1|               1.0|                   4|                       0|                       4|     2023-02-22|I love the conven...|Convenient and ma...|     fair|    green|combination|     black|   P467976|(Re)setting 100% ...|Supergoop!|     35.0|            1|  Cold|
|         6|42900077123|     5|             1|               1.0|                   4|                       0|                       4|     2023-02-21|I love this!! I w...|Amazing for touch...|     fair|    green|       oily|     brown|   P467976|(Re)setting 100% ...|Supergoop!|     35.0|            1|  Cold|
|         7| 2205673874|     1|             0|               0.0|                   2|                       2|                       0|     2023-02-17|Trash. Super diff...|              Trash.|    light|    brown|combination|     brown|   P467976|(Re)setting 100% ...|Supergoop!|     35.0|            1|  Cold|
|         8| 1576670382|     5|             1|               0.5|                   2|                       1|                       1|     2023-02-17|I have been using...|      Great product!|    light|     blue|     normal|    blonde|   P467976|(Re)setting 100% ...|Supergoop!|     35.0|            1|  Cold|
|         9| 2260142001|     5|             1|               1.0|                   2|                       0|                       2|     2023-02-11|I used this as a ...| Great for touch ups|    light|    hazel|       oily|    blonde|   P467976|(Re)setting 100% ...|Supergoop!|     35.0|            1|  Cold|
+----------+-----------+------+--------------+------------------+--------------------+------------------------+------------------------+---------------+--------------------+--------------------+---------+---------+-----------+----------+----------+--------------------+----------+---------+-------------+------+
only showing top 10 rows
+----------+-----------+------+--------------+------------------+--------------------+------------------------+------------------------+---------------+--------------------+--------------------+-----------+---------+-----------+----------+----------+--------------------+----------+---------+-------------+------+
|Unnamed: 0|  author_id|rating|is_recommended|       helpfulness|total_feedback_count|total_neg_feedback_count|total_pos_feedback_count|submission_time|         review_text|        review_title|  skin_tone|eye_color|  skin_type|hair_color|product_id|        product_name|brand_name|price_usd|is_cold_month|season|
+----------+-----------+------+--------------+------------------+--------------------+------------------------+------------------------+---------------+--------------------+--------------------+-----------+---------+-----------+----------+----------+--------------------+----------+---------+-------------+------+
|         0| 1945004256|     5|             1|               0.0|                   2|                       2|                       0|     2022-12-10|I absolutely L-O-...|        A must have!|lightMedium|    green|combination|      NULL|   P379064|Lotus Balancing &...|   Clarins|     65.0|            0|  Warm|
|         1| 5478482359|     3|             1|0.3333329856395721|                   3|                       2|                       1|     2021-12-17|I gave this 3 sta...|it keeps oily ski...|  mediumTan|    brown|       oily|     black|   P379064|Lotus Balancing &...|   Clarins|     65.0|            0|  Warm|
|         2|29002209922|     5|             1|               1.0|                   2|                       0|                       2|     2021-06-07|Works well as soo...|    Worth the money!|lightMedium|    brown|        dry|     black|   P379064|Lotus Balancing &...|   Clarins|     65.0|            0|  Warm|
|         3| 7391078463|     5|             1|               1.0|                   2|                       0|                       2|     2021-05-21|this oil helped w...|       best face oil|lightMedium|    brown|combination|    blonde|   P379064|Lotus Balancing &...|   Clarins|     65.0|            0|  Warm|
|         4| 1766313888|     5|             1|               1.0|                  13|                       0|                      13|     2021-03-29|This is my first ...|      Maskne miracle|  mediumTan|    brown|combination|     black|   P379064|Lotus Balancing &...|   Clarins|     65.0|            1|  Cold|
|         5| 1532951999|     5|             1|               1.0|                   5|                       0|                       5|     2020-09-20|I have  been usin...|            Best Oil|lightMedium|    brown|     normal|     brown|   P379064|Lotus Balancing &...|   Clarins|     65.0|            0|  Warm|
|         6| 2168991896|     5|             1|0.8999999761581421|                  10|                       1|                       9|     2020-08-20|I first used the ...|Shame on me for w...|lightMedium|    brown|combination|     black|   P379064|Lotus Balancing &...|   Clarins|     65.0|            0|  Warm|
|         7| 5240639417|     5|             1|0.9333329796791076|                  15|                       1|                      14|     2020-08-01|Super short back ...|My favorite for m...|       fair|     blue|combination|    blonde|   P379064|Lotus Balancing &...|   Clarins|     65.0|            0|  Warm|
|         8| 1599604155|     5|             1|               1.0|                   4|                       0|                       4|     2020-06-07|first oil that I’...|                NULL|      light|    hazel|combination|     brown|   P379064|Lotus Balancing &...|   Clarins|     65.0|            0|  Warm|
|         9|11792701494|     5|             1|0.9166669845581056|                  12|                       1|                      11|     2020-04-03|This is the best ...|  Best treatment oil|lightMedium|    brown|combination|     brown|   P379064|Lotus Balancing &...|   Clarins|     65.0|            1|  Cold|
+----------+-----------+------+--------------+------------------+--------------------+------------------------+------------------------+---------------+--------------------+--------------------+-----------+---------+-----------+----------+----------+--------------------+----------+---------+-------------+------+
only showing top 10 rows

In [17]:
# UNION ALL review tables into total_reviews_df
total_reviews_df = spark.sql("""
    SELECT * FROM reviews_1_df
    UNION ALL
    SELECT * FROM reviews_2_df
    UNION ALL
    SELECT * FROM reviews_3_df
    UNION ALL
    SELECT * FROM reviews_4_df
    UNION ALL
    SELECT * FROM reviews_5_df
""")
total_reviews_df.show(10)
total_reviews_df.createOrReplaceTempView("total_reviews_df")

+----------+-----------+------+--------------+-----------+--------------------+------------------------+------------------------+---------------+--------------------+--------------------+-----------+---------+-----------+----------+----------+--------------------+----------+---------+-------------+------+
|Unnamed: 0|  author_id|rating|is_recommended|helpfulness|total_feedback_count|total_neg_feedback_count|total_pos_feedback_count|submission_time|         review_text|        review_title|  skin_tone|eye_color|  skin_type|hair_color|product_id|        product_name|brand_name|price_usd|is_cold_month|season|
+----------+-----------+------+--------------+-----------+--------------------+------------------------+------------------------+---------------+--------------------+--------------------+-----------+---------+-----------+----------+----------+--------------------+----------+---------+-------------+------+
|         0| 1741593524|     5|             1|        1.0|                   2|                       0|                       2|     2023-02-01|I use this with t...|Taught me how to ...|       NULL|    brown|        dry|     black|   P504322|Gentle Hydra-Gel ...|  NUDESTIX|     19.0|            1|  Cold|
|         1|31423088263|     1|             0|       NULL|                   0|                       0|                       0|     2023-03-21|I bought this lip...|        Disappointed|       NULL|     NULL|       NULL|      NULL|   P420652|Lip Sleeping Mask...|   LANEIGE|     24.0|            1|  Cold|
|         2| 5061282401|     5|             1|       NULL|                   0|                       0|                       0|     2023-03-21|My review title s...|New Favorite Routine|      light|    brown|        dry|    blonde|   P420652|Lip Sleeping Mask...|   LANEIGE|     24.0|            1|  Cold|
|         3| 6083038851|     5|             1|       NULL|                   0|                       0|                       0|     2023-03-20|I’ve always loved...|Can't go wrong wi...|       NULL|    brown|combination|     black|   P420652|Lip Sleeping Mask...|   LANEIGE|     24.0|            1|  Cold|
|         4|47056667835|     5|             1|       NULL|                   0|                       0|                       0|     2023-03-20|If you have dry c...|     A must have !!!|      light|    hazel|combination|      NULL|   P420652|Lip Sleeping Mask...|   LANEIGE|     24.0|            1|  Cold|
|         5|42802569154|     4|             1|        1.0|                   1|                       0|                       1|     2023-03-19|The scent isn’t m...|              Great!|lightMedium|    brown|     normal|     brown|   P420652|Lip Sleeping Mask...|   LANEIGE|     24.0|            1|  Cold|
|         6| 6941883808|     2|             0|       0.25|                   8|                       6|                       2|     2023-03-19|I’ll give this 2 ...|Dried my lips out...|      light|     blue|combination|     brown|   P420652|Lip Sleeping Mask...|   LANEIGE|     24.0|            1|  Cold|
|         7|27926227988|     5|             1|       NULL|                   0|                       0|                       0|     2023-03-19|I use this at nig...|         Works great|  fairLight|    brown|combination|     brown|   P420652|Lip Sleeping Mask...|   LANEIGE|     24.0|            1|  Cold|
|         8| 7656791726|     5|             1|        1.0|                   1|                       0|                       1|     2023-03-18|I love this stuff...|          Must have.|      light|     blue|     normal|    blonde|   P420652|Lip Sleeping Mask...|   LANEIGE|     24.0|            1|  Cold|
|         9|38727834382|     5|             1|        1.0|                   2|                       0|                       2|     2023-03-18|I purchased the S...|     RUN TO PURCHASE|      light|    brown|     normal|     brown|   P420652|Lip Sleeping Mask...|   LANEIGE|     24.0|            1|  Cold|
+----------+-----------+------+--------------+-----------+--------------------+------------------------+------------------------+---------------+--------------------+--------------------+-----------+---------+-----------+----------+----------+--------------------+----------+---------+-------------+------+
only showing top 10 rows

In [18]:
# Calculate product_id sales revenue in 2022-2023
sales_revenue = spark.sql("""
SELECT 
    product_id,
    product_name,
    brand_name,
    SUM(price_usd) AS total_revenue
FROM total_reviews_df
WHERE YEAR(TRY_CAST(submission_time AS TIMESTAMP)) BETWEEN 2020 AND 2023
GROUP BY product_id, product_name, brand_name
ORDER BY total_revenue DESC;
""")

sales_revenue.show()

[Stage 19:========================>                              (24 + 12) / 54]

+----------+--------------------+--------------------+-------------+
|product_id|        product_name|          brand_name|total_revenue|
+----------+--------------------+--------------------+-------------+
|   P375849|Facial Treatment ...|               SK-II|     481915.0|
|   P461933|Advanced Night Re...|        Estée Lauder|     470145.0|
|   P433520|Magic Cream Moist...|   Charlotte Tilbury|     282000.0|
|   P416341|Crème de la Mer M...|              La Mer|     281580.0|
|   P423688|Daily Microfolian...|         Dermalogica|     278265.0|
|   P461159|Estee Lauder Adva...|        Estée Lauder|     277265.0|
|   P479839|Revitalizing Supr...|        Estée Lauder|     272538.0|
|   P309308|Good Genes All-In...|        Sunday Riley|     267546.0|
|   P456213|GOOPGLOW Microder...|                goop|     265625.0|
|   P447212|    Hyaluronic Serum|   Dr. Barbara Sturm|     252160.0|
|   P460779|Skinlongevity Lon...|        bareMinerals|     242190.0|
|   P461949|The Concentrate S...|              La Mer|     238850.0|
|   P269122|Alpha Beta Extra ...|Dr. Dennis Gross ...|     219696.0|
|   P421235|Double Serum Firm...|             Clarins|     196740.0|
|   P426183|Mini Facial Treat...|               SK-II|     194535.0|
|   P420652|Lip Sleeping Mask...|             LANEIGE|     187344.0|
|   P447781|          Face Cream|   Dr. Barbara Sturm|     180900.0|
|   P474953|Abeille Royale Ad...|            GUERLAIN|     178930.0|
|   P427421|Protini Polypepti...|      Drunk Elephant|     178704.0|
|   P450271|Green Clean Makeu...|             Farmacy|     178440.0|
+----------+--------------------+--------------------+-------------+
only showing top 20 rows

In [19]:
# Calculate product_id median sales revenue from 2022-2023 and compare to overall brand_name revenue

median_products = spark.sql("""
    WITH sales_revenue AS (
        SELECT 
            product_id,
            product_name,
            brand_name,
            SUM(review_count * price_usd) AS total_revenue
        FROM (
            SELECT 
                product_id,
                product_name, 
                brand_name,
                author_id, 
                COUNT(*) AS review_count, 
                price_usd
            FROM total_reviews_df
            WHERE YEAR(TRY_CAST(submission_time AS TIMESTAMP)) BETWEEN 2022 AND 2023
            GROUP BY product_id, product_name, brand_name, author_id, price_usd
        ) subquery
        GROUP BY product_id, product_name, brand_name
    ),

    brand_revenue AS (
        SELECT 
            brand_name,
            SUM(total_revenue) AS brand_total_revenue
        FROM sales_revenue
        GROUP BY brand_name
    ),

    median_sales AS (
        SELECT percentile_approx(total_revenue, 0.5) AS median_revenue FROM sales_revenue
    )

    SELECT 
        sr.product_id, 
        sr.product_name, 
        sr.brand_name, 
        sr.total_revenue,
        (br.brand_total_revenue - sr.total_revenue) AS brand_total_revenue,
        ROUND((sr.total_revenue / br.brand_total_revenue) * 100, 2) AS percentage_difference
    FROM sales_revenue sr
    JOIN brand_revenue br ON sr.brand_name = br.brand_name
    JOIN median_sales ms ON sr.total_revenue = ms.median_revenue
""")

median_products.show()

[Stage 22:===>           (14 + 12) / 54][Stage 23:>                (0 + 0) / 54]

[Stage 22:===============>(53 + 1) / 54][Stage 23:>               (0 + 11) / 54]

[Stage 23:===============>                                       (15 + 12) / 54]

[Stage 23:========>      (32 + 12) / 54][Stage 25:>                (0 + 0) / 12]

+----------+--------------------+------------------+-------------+-------------------+---------------------+
|product_id|        product_name|        brand_name|total_revenue|brand_total_revenue|percentage_difference|
+----------+--------------------+------------------+-------------+-------------------+---------------------+
|   P442990|Clean Screen Mine...|REN Clean Skincare|        880.0|            75904.0|                 1.15|
|   P442713|FAB Skin Lab Reti...|  First Aid Beauty|        880.0|            71344.0|                 1.22|
|   P501323|Overnight Recover...|            Tatcha|        880.0|           255889.0|                 0.34|
|   P453929|Retinol Youth Ren...|             Murad|        880.0|           205419.0|                 0.43|
|   P467123|That Big Screen M...|        JLo Beauty|        880.0|            50974.0|                  1.7|
+----------+--------------------+------------------+-------------+-------------------+---------------------+

In [20]:
# Monthly Revenue Comparison: Product P442990 vs. REN Clean Skincare (2020-2023)

monthly_revenue_comparison = spark.sql("""
    WITH sales_revenue AS (
        SELECT  
            DATE_FORMAT(TRY_CAST(submission_time AS TIMESTAMP), 'yyyy-MM') AS month, 
            SUM(price_usd) AS total_revenue_product
        FROM total_reviews_df
        WHERE YEAR(TRY_CAST(submission_time AS TIMESTAMP)) BETWEEN 2020 AND 2023
            AND product_id = 'P442990'
        GROUP BY DATE_FORMAT(TRY_CAST(submission_time AS TIMESTAMP), 'yyyy-MM')
    ),

    brand_revenue AS (
        SELECT 
            DATE_FORMAT(TRY_CAST(submission_time AS TIMESTAMP), 'yyyy-MM') AS month,
            SUM(review_count * price_usd) AS total_revenue_brand
        FROM (
            SELECT 
                brand_name,
                submission_time,
                COUNT(*) AS review_count, 
                price_usd
            FROM total_reviews_df
            WHERE YEAR(TRY_CAST(submission_time AS TIMESTAMP)) BETWEEN 2020 AND 2023
                AND brand_name = 'REN Clean Skincare'
            GROUP BY brand_name, submission_time, price_usd
        ) subquery
        GROUP BY DATE_FORMAT(TRY_CAST(submission_time AS TIMESTAMP), 'yyyy-MM')
    )

    SELECT 
        COALESCE(sr.month, br.month) AS month,
        COALESCE(sr.total_revenue_product, 0) AS total_revenue_product,
        COALESCE(br.total_revenue_brand, 0) AS total_revenue_brand
    FROM sales_revenue sr
    FULL OUTER JOIN brand_revenue br ON sr.month = br.month
    ORDER BY month;
""").toPandas()

monthly_revenue_comparison["month"] = pd.to_datetime(monthly_revenue_comparison["month"])

fig, ax1 = plt.subplots(figsize=(12, 6))

ax1.bar(monthly_revenue_comparison["month"], monthly_revenue_comparison["total_revenue_product"], 
        width=20, alpha=0.6, label="Product P442990 (Bar)", color="darkblue")
ax1.bar(monthly_revenue_comparison["month"], monthly_revenue_comparison["total_revenue_brand"], 
        width=20, alpha=0.4, label="REN Clean Skincare (Bar)", color="darkred")

ax2 = ax1.twinx()
ax2.plot(monthly_revenue_comparison["month"], monthly_revenue_comparison["total_revenue_product"], 
         marker="o", linestyle="-", label="Product P442990 (Line)", color="darkblue")
ax2.plot(monthly_revenue_comparison["month"], monthly_revenue_comparison["total_revenue_brand"], 
         marker="s", linestyle="--", label="REN Clean Skincare (Line)", color="darkred")

ax1.set_xlabel("Month")
ax1.set_ylabel("Total Revenue (USD) - Bar Chart", color="black")
ax2.set_ylabel("Total Revenue (USD) - Line Chart", color="black")

ax1.set_title("Monthly Revenue Comparison: Product P442990 vs. REN Clean Skincare (2020-2023)")
ax1.set_xticks(monthly_revenue_comparison["month"])
ax1.set_xticklabels(monthly_revenue_comparison["month"].dt.strftime('%b-%Y'), rotation=45)

ax1.legend(loc="upper left")
ax2.legend(loc="upper right")

plt.tight_layout()
plt.savefig(f"{home_dir}/assets/fig6_monthly_revenue.png", dpi=150, bbox_inches="tight")
plt.show()

[Stage 46:====================================================>   (51 + 3) / 54]

/var/folders/qd/bdj1245s6yjgfq0g9fxz8n4m0000gn/T/ipykernel_82775/55994985.py:69: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [21]:
# Complementary product_id and brand_name bought by same author_id that bought Product P442990

complementary_products = spark.sql("""
WITH target_customers AS (
    SELECT DISTINCT author_id
    FROM total_reviews_df
    WHERE product_id = 'P442990'
),
complementary_purchases AS (
    SELECT DISTINCT tr.author_id, tr.product_id, tr.product_name, tr.brand_name
    FROM total_reviews_df tr
    JOIN target_customers tc ON tr.author_id = tc.author_id
    WHERE tr.product_id != 'P442990'
)
SELECT 
    product_id, 
    product_name,
    brand_name, 
    COUNT(*) AS purchase_count
FROM complementary_purchases
GROUP BY product_id, product_name, brand_name
ORDER BY purchase_count DESC;
""")

complementary_products.createOrReplaceTempView("complementary_products")
complementary_products.show()

[Stage 62:===>           (12 + 12) / 54][Stage 63:>                (0 + 0) / 54]

[Stage 62:=======>       (27 + 12) / 54][Stage 63:>                (0 + 0) / 54]

[Stage 63:>                                                       (0 + 12) / 54]

+----------+--------------------+-------------------+--------------+
|product_id|        product_name|         brand_name|purchase_count|
+----------+--------------------+-------------------+--------------+
|   P420652|Lip Sleeping Mask...|            LANEIGE|            23|
|   P417238|Green Clean Makeu...|            Farmacy|            16|
|   P450271|Green Clean Makeu...|            Farmacy|            16|
|   P470255|Mini Unseen Sunsc...|         Supergoop!|            13|
|   P454380|Unseen Sunscreen ...|         Supergoop!|            13|
|   P427417|Niacinamide 10% +...|       The Ordinary|            13|
|   P427421|Protini Polypepti...|     Drunk Elephant|            12|
|   P428095|Ready Steady Glow...| REN Clean Skincare|            12|
|   P465368|Mini Ready Steady...| REN Clean Skincare|            12|
|   P419221|Umbra Tinte Physi...|     Drunk Elephant|            12|
|   P456398|Ultimate Sun Prot...|           Shiseido|            11|
|   P394639|The True Cream Aq...|              belif|            11|
|   P427419|Hyaluronic Acid 2...|       The Ordinary|            11|
|   P429952|        Jet Lag Mask|     Summer Fridays|            11|
|   P480630|   Mini Jet Lag Mask|     Summer Fridays|            11|
|   P411387|Superfood Antioxi...|Youth To The People|            10|
|   P441644|Mini Superfood An...|Youth To The People|            10|
|   P442563|AHA 30% + BHA 2% ...|       The Ordinary|            10|
|   P418218|The Water Cream O...|             Tatcha|             9|
|   P454794|Mini The Water Cream|             Tatcha|             9|
+----------+--------------------+-------------------+--------------+
only showing top 20 rows

In [22]:
# List ingredients from Product P442990

ingredients = spark.sql("""
SELECT 
    ingredients
FROM product_df
WHERE product_id = 'P442990';
""")

ingredients.show(truncate=False)

+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|ingredients                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|['Aqua (Water), Zinc Oxide, Caprylic/Capric Triglyceride, Aloe Barbadensis Leaf Juice, Glycerin, Caprylyl Caprylate/Caprate, Propanediol, Arachidyl Alcohol, Cetearyl Alcohol, Coco-Glucoside, Oryza Sativa Starch, Pongamia Glabra Seed Oil, Microcrystalline Cellulose, Behenyl Alcohol, Phenoxyethanol, Arachidyl Glucoside, Isostearic Acid, Lecithin, Polyglyceryl-3 Polyricinoleate, Polyhydroxystearic Acid, Passiflora Edulis Fruit Extract, Ethylhexylglycerin, Glyceryl Oleate, Vaccinium Macrocarpon (Cranberry) Seed Oil, Xanthan Gum, Cellulose Gum, Sodium Chloride, Hippophae Rhamnoides Oil, Citrus Nobilis (Mandarin Orange) Peel Oil, Anthemis Nobilis Flower Oil, Cinnamomum Camphora Linalloliferum (Ho Wood) Leaf Oil, Pelargonium Graveolens Flower Oil, Glucose, Parfum* (Fragrance), Helianthus Annuus (Sunflower) Seed Oil, Tocopherol, Rosmarinus Officinalis (Rosmary) Leaf Extract, Hydrogenated Palm Glycerides Citrate, Citric Acid, Sodium Hydroxide, Citronellol, Geraniol, Limonene, Linalool.']|
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

### **Product P442990 Key Ingredients and Their Effects in Cold Months (January-April)**  

1. **Aqua (Water)** – The primary solvent in the formulation, providing a base for other ingredients to dissolve and ensuring hydration.  

2. **Zinc Oxide** – A mineral UV filter with anti-inflammatory properties, helping to protect and soothe winter-stressed skin while offering sun protection against winter sun exposure.  

3. **Caprylic/Capric Triglyceride** – Derived from coconut oil, this lightweight emollient forms a protective layer on the skin, preventing moisture loss in cold and dry weather.  

4. **Aloe Barbadensis (Aloe Vera) Leaf Juice** – A natural hydrator that soothes irritation, reduces redness, and provides deep moisture, beneficial for winter-induced dryness.  

5. **Glycerin** – A powerful humectant that pulls moisture into the skin, helping to prevent dehydration caused by cold air and indoor heating.  

6. **Caprylyl Caprylate/Caprate** – A skin-conditioning agent that improves moisture retention and smoothens the skin’s surface.  

7. **Propanediol** – A humectant that enhances hydration and increases the penetration of other beneficial ingredients.  

8. **Arachidyl Alcohol** – A fatty alcohol that acts as an emollient, providing a rich and creamy texture to formulations and helping maintain skin hydration.  

9. **Cetearyl Alcohol** – A non-drying fatty alcohol that stabilizes emulsions and provides skin-softening benefits, essential in combating winter roughness.  

10. **Coco-Glucoside** – A mild surfactant derived from coconut, offering gentle cleansing without stripping the skin’s natural moisture.  

11. **Oryza Sativa (Rice) Starch** – Absorbs excess oil while providing a soft, velvety texture to the skin, ensuring comfort in winter formulations.  

12. **Pongamia Glabra (Karanja) Seed Oil** – Known for its UV-protective and antibacterial properties, it helps defend the skin against environmental stressors in cold months.  

13. **Microcrystalline Cellulose** – Acts as a texture enhancer, providing a smooth feel while absorbing excess oil.  

14. **Behenyl Alcohol** – A fatty alcohol that adds conditioning properties, keeping the skin soft and hydrated in cold weather.  

15. **Phenoxyethanol** – A preservative that prevents microbial growth, ensuring the product’s stability across different temperatures.  

16. **Arachidyl Glucoside** – Works as an emulsifier to maintain product consistency and stability during seasonal changes.  

17. **Isostearic Acid** – Helps emulsify and stabilize formulations while enhancing the spreadability of products.  

18. **Lecithin** – A phospholipid that supports moisture retention, reinforcing the skin barrier against winter dryness.  

19. **Polyglyceryl-3 Polyricinoleate** – A plant-derived emulsifier that enhances the stability of water and oil components.  

20. **Polyhydroxystearic Acid** – Works as a dispersing agent for mineral ingredients like Zinc Oxide, ensuring even application and protection against winter sun damage.  

21. **Passiflora Edulis (Passionfruit) Fruit Extract** – Rich in antioxidants, it helps protect against free radicals while providing nourishment for winter-exposed skin.  

22. **Ethylhexylglycerin** – A skin-conditioning agent that enhances hydration while boosting the effectiveness of preservatives.  

23. **Glyceryl Oleate** – An emulsifier that helps restore the skin’s natural lipids, preventing winter dryness.  

24. **Vaccinium Macrocarpon (Cranberry) Seed Oil** – High in antioxidants and omega fatty acids, it strengthens the skin’s barrier and protects against harsh winter elements.  

25. **Xanthan Gum** – A thickening agent that improves product texture and moisture retention.  

26. **Cellulose Gum** – Provides texture enhancement and hydration benefits.  

27. **Sodium Chloride** – Acts as a stabilizer, maintaining the product’s consistency across different temperatures.  

28. **Hippophae Rhamnoides (Sea Buckthorn) Oil** – Rich in essential fatty acids and vitamins, it supports skin regeneration and combats winter-induced irritation.  

29. **Citrus Nobilis (Mandarin Orange) Peel Oil** – Offers antioxidant benefits while providing a refreshing natural fragrance.  

30. **Anthemis Nobilis (Chamomile) Flower Oil** – Known for its anti-inflammatory and soothing effects, it helps calm winter skin sensitivity.  

31. **Cinnamomum Camphora Linalloliferum (Ho Wood) Leaf Oil** – Provides antibacterial properties while maintaining hydration.  

32. **Pelargonium Graveolens (Geranium) Flower Oil** – A balancing essential oil that soothes irritation and promotes hydration.  

33. **Glucose** – A humectant that enhances skin hydration by attracting moisture, ideal for combating winter dryness.  

34. **Parfum (Fragrance)** – Adds a pleasant scent, though some components may cause sensitivity in dry winter conditions.  

35. **Helianthus Annuus (Sunflower) Seed Oil** – A rich source of linoleic acid that reinforces the skin barrier, helping prevent moisture loss in cold weather.  

36. **Tocopherol (Vitamin E)** – A powerful antioxidant that protects against free radicals while nourishing and repairing dry, winter-stressed skin.  

37. **Rosmarinus Officinalis (Rosemary) Leaf Extract** – Has natural antioxidant and antimicrobial properties, promoting skin protection.  

38. **Hydrogenated Palm Glycerides Citrate** – A conditioning agent that enhances skin softness and moisture retention.  

39. **Citric Acid** – Helps balance pH levels and provides mild exfoliation, promoting a healthy skin barrier.  

40. **Sodium Hydroxide** – A pH adjuster that ensures the product remains gentle on the skin.  

41. **Citronellol, Geraniol, Limonene, Linalool** – Naturally occurring fragrance components with antioxidant properties but may cause sensitivity in dry winter skin.  

### **Effects in Cold Months**  
- **Hydration & Moisture Retention**: Ingredients like Glycerin, Aloe Vera, Caprylic/Capric Triglyceride, and Sunflower Seed Oil help maintain hydration.  
- **Barrier Protection & Repair**: Cranberry Seed Oil, Sea Buckthorn Oil, and Vitamin E support the skin barrier against winter-induced irritation.  
- **Anti-Inflammatory & Soothing Properties**: Chamomile Oil, Geranium Oil, and Aloe Vera reduce redness and irritation caused by cold weather.  
- **Antioxidant Defense**: Zinc Oxide, Passionfruit Extract, and Rosemary Leaf Extract help protect against environmental stressors.  
- **Potential Sensitivity**: Fragrance compounds like Citronellol, Limonene, and Geraniol may cause irritation in very dry or sensitive skin.  

### **Best Uses for Cold Months**  
- **Hydrating Creams & Moisturizers**: To maintain moisture levels and prevent dryness.  
- **Barrier-Repairing Oils & Serums**: Cranberry Seed Oil, Sea Buckthorn Oil, and Vitamin E help strengthen the skin.  
- **Soothing Treatments & Masks**: Aloe Vera, Chamomile, and Geranium Oil calm winter-related redness and irritation.  
- **Avoiding Harsh Exfoliation**: The skin is more vulnerable in cold months, so gentle care is necessary.

### **Estimated Standard Concentrations**

#### **Base of the Formula**  
- **Aqua (Water)** – 50-80%  

#### **Active Ingredients**  
- **Zinc Oxide** – 5-25% (Used in sunscreens)  

#### **Emollients & Moisturizers**  
- **Caprylic/Capric Triglyceride** – 2-10%  
- **Caprylyl Caprylate/Caprate** – 1-3%  
- **Cetearyl Alcohol** – 2-5%  
- **Behenyl Alcohol** – 1-5%  
- **Glyceryl Oleate** – 0.5-2%  
- **Helianthus Annuus (Sunflower) Seed Oil** – 0.5-2%  
- **Hydrogenated Palm Glycerides Citrate** – 0.1-1%  

#### **Soothing & Hydrating Agents**  
- **Aloe Barbadensis Leaf Juice** – 1-5%  
- **Glycerin** – 2-10%  
- **Anthemis Nobilis (Chamomile) Flower Oil** – 0.1-1%  

#### **Emulsifiers & Stabilizers**  
- **Arachidyl Alcohol** – 0.5-3%  
- **Arachidyl Glucoside** – 0.5-2%  
- **Isostearic Acid** – 0.5-3%  
- **Lecithin** – 0.1-2%  
- **Polyglyceryl-3 Polyricinoleate** – 0.5-2%  
- **Polyhydroxystearic Acid** – 0.5-3%  

#### **Surfactants & Texture Enhancers**  
- **Coco-Glucoside** – 0.5-2%  
- **Microcrystalline Cellulose** – 0.5-3%  
- **Oryza Sativa Starch (Rice Starch)** – 0.5-2%  

#### **Antioxidants & UV Protection**  
- **Pongamia Glabra Seed Oil** – 1-3%  
- **Passiflora Edulis Fruit Extract** – 0.1-2%  
- **Vaccinium Macrocarpon (Cranberry) Seed Oil** – 0.1-1%  
- **Hippophae Rhamnoides (Sea Buckthorn) Oil** – 0.1-1%  
- **Tocopherol (Vitamin E)** – 0.1-1%  
- **Rosmarinus Officinalis (Rosemary) Leaf Extract** – 0.1-1%  

#### **Humectants & Solvents**  
- **Propanediol** – 1-5%  
- **Glucose** – 0.1-1%  

#### **Thickeners & Viscosity Adjusters**  
- **Xanthan Gum** – 0.1-1%  
- **Cellulose Gum** – 0.1-1%  
- **Sodium Chloride** – 0.1-2%  

#### **pH Adjusters**  
- **Citric Acid** – 0.1-1%  
- **Sodium Hydroxide** – 0.1-1%  

#### **Preservatives & Preservative Boosters**  
- **Phenoxyethanol** – 0.5-1%  
- **Ethylhexylglycerin** – 0.3-1%  

#### **Fragrances & Essential Oils**  
- **Citrus Nobilis (Mandarin Orange) Peel Oil** – 0.1-1%  
- **Cinnamomum Camphora Linalloliferum (Ho Wood) Leaf Oil** – 0.1-1%  
- **Pelargonium Graveolens Flower Oil** – 0.1-1%  
- **Parfum (Fragrance)** – 0.1-1%  
- **Citronellol, Geraniol, Limonene, Linalool** – 0.01-0.5% (Fragrance components)

In [23]:
# Separating oz and mL values

separated_sizes = spark.sql('''
SELECT 
    product_id,
    product_name,
    brand_name,
    size,
    split(size, ' ')[0] AS oz_value,
    CASE 
        WHEN split(size, ' ')[2] = 'mL' THEN split(size, ' ')[1]
        WHEN split(size, ' ')[3] = 'mL' THEN split(size, ' ')[2]
        WHEN split(size, ' ')[4] = 'mL' THEN split(size, ' ')[3]
        WHEN split(size, ' ')[5] = 'mL' THEN split(size, ' ')[4]
        WHEN split(size, ' ')[6] = 'mL' THEN split(size, ' ')[5]
    END AS mL_value
FROM product_df
WHERE size RLIKE '(oz|mL)';
''')
separated_sizes.createOrReplaceTempView("separated_sizes")
separated_sizes.show(truncate=False)

+----------+--------------------------------------------------------+----------+---------------+--------+--------+
|product_id|product_name                                            |brand_name|size           |oz_value|mL_value|
+----------+--------------------------------------------------------+----------+---------------+--------+--------+
|P473668   |La Habana Eau de Parfum                                 |19-69     |3.4 oz/ 100 mL |3.4     |100     |
|P473662   |Rainbow Bar Eau de Parfum                               |19-69     |3.4 oz/ 100 mL |3.4     |100     |
|P473660   |Kasbah Eau de Parfum                                    |19-69     |3.4 oz/ 100 mL |3.4     |100     |
|P473658   |Purple Haze Eau de Parfum                               |19-69     |3.4 oz/ 100 mL |3.4     |100     |
|P473661   |Kasbah Eau de Parfum Travel Spray                       |19-69     |0.25 oz/ 7.5 mL|0.25    |7.5     |
|P473659   |Purple Haze Eau de Parfum Travel Spray                  |19-69     |0.25 oz/ 7.5 mL|0.25    |7.5     |
|P473666   |Invisible Post Eau de Parfum                            |19-69     |3.4 oz/ 100 mL |3.4     |100     |
|P472300   |Capri Eau de Parfum                                     |19-69     |3.4 oz/ 100 mL |3.4     |100     |
|P473667   |Invisible Post Eau de Parfum Travel Spray               |19-69     |0.25 oz/ 7.5 mL|0.25    |7.5     |
|P473663   |Rainbow Bar Eau de Parfum Travel Spray                  |19-69     |0.25 oz/ 7.5 mL|0.25    |7.5     |
|P473670   |Capri Eau de Parfum Travel Spray                        |19-69     |0.25 oz/ 7.5 mL|0.25    |7.5     |
|P473664   |L'air Barbes Eau de Parfum                              |19-69     |3.4 oz/ 100 mL |3.4     |100     |
|P473665   |L'air Barbes Eau de Parfum Travel Spray                 |19-69     |0.25 oz/ 7.5 mL|0.25    |7.5     |
|P476416   |AFRICAN Beauty Butter- Intensive Dry Skin Treatment     |54 Thrones|6 oz / 180 mL  |6       |180     |
|P503832   |Mini AFRICAN Beauty Butter- Intensive Dry Skin Treatment|54 Thrones|1 oz / 30 mL   |1       |30      |
|P483139   |The Cape Perfume                                        |ABBOTT    |1.7 oz / 50 mL |1.7     |50      |
|P483079   |Crescent Beach Perfume                                  |ABBOTT    |1.7 oz / 50 mL |1.7     |50      |
|P483130   |Sequoia Perfume                                         |ABBOTT    |1.7 oz / 50 mL |1.7     |50      |
|P483072   |Big Sky Eau de Parfum Travel Spray                      |ABBOTT    |0.27 oz / 8 mL |0.27    |8       |
|P483071   |Big Sky Eau de Parfum                                   |ABBOTT    |1.7 oz / 50 mL |1.7     |50      |
+----------+--------------------------------------------------------+----------+---------------+--------+--------+
only showing top 20 rows

In [24]:
# Calculate concentration (size * standard_conc_percentage) of each ingredient in Product P442990

ingredient_concentrations = spark.sql("""
    SELECT * FROM VALUES
        ('Aqua (Water)', 0.65),
        ('Zinc Oxide', 0.15),
        ('Caprylic/Capric Triglyceride', 0.06),
        ('Aloe Barbadensis Leaf Juice', 0.03),
        ('Glycerin', 0.06),
        ('Caprylyl Caprylate/Caprate', 0.02),
        ('Propanediol', 0.03),
        ('Arachidyl Alcohol', 0.0175),
        ('Cetearyl Alcohol', 0.035),
        ('Coco-Glucoside', 0.015),
        ('Oryza Sativa Starch', 0.015),
        ('Pongamia Glabra Seed Oil', 0.02),
        ('Microcrystalline Cellulose', 0.0175),
        ('Behenyl Alcohol', 0.03),
        ('Phenoxyethanol', 0.0075),
        ('Arachidyl Glucoside', 0.0125),
        ('Isostearic Acid', 0.0175),
        ('Lecithin', 0.0105),
        ('Polyglyceryl-3 Polyricinoleate', 0.0125),
        ('Polyhydroxystearic Acid', 0.0175),
        ('Passiflora Edulis Fruit Extract', 0.0105),
        ('Ethylhexylglycerin', 0.0065),
        ('Glyceryl Oleate', 0.0125),
        ('Vaccinium Macrocarpon (Cranberry) Seed Oil', 0.0055),
        ('Xanthan Gum', 0.0055),
        ('Cellulose Gum', 0.0055),
        ('Sodium Chloride', 0.0105),
        ('Hippophae Rhamnoides Oil', 0.0055),
        ('Citrus Nobilis (Mandarin Orange) Peel Oil', 0.0055),
        ('Anthemis Nobilis Flower Oil', 0.0055),
        ('Cinnamomum Camphora Linalloliferum (Ho Wood) Leaf Oil', 0.0055),
        ('Pelargonium Graveolens Flower Oil', 0.0055),
        ('Glucose', 0.0055),
        ('Parfum* (Fragrance)', 0.0055),
        ('Helianthus Annuus (Sunflower) Seed Oil', 0.0125),
        ('Tocopherol', 0.0055),
        ('Rosmarinus Officinalis (Rosmary) Leaf Extract', 0.0055),
        ('Hydrogenated Palm Glycerides Citrate', 0.0055),
        ('Citric Acid', 0.0055),
        ('Sodium Hydroxide', 0.0055),
        ('Citronellol', 0.00255),
        ('Geraniol', 0.00255),
        ('Limonene', 0.00255),
        ('Linalool', 0.00255)
    AS ingredient(ingredient, standard_conc_percentage)
""")
ingredient_concentrations.createOrReplaceTempView("ingredient_concentrations")
ingredient_concentrations.show(10)

+--------------------+------------------------+
|          ingredient|standard_conc_percentage|
+--------------------+------------------------+
|        Aqua (Water)|                 0.65000|
|          Zinc Oxide|                 0.15000|
|Caprylic/Capric T...|                 0.06000|
|Aloe Barbadensis ...|                 0.03000|
|            Glycerin|                 0.06000|
|Caprylyl Caprylat...|                 0.02000|
|         Propanediol|                 0.03000|
|   Arachidyl Alcohol|                 0.01750|
|    Cetearyl Alcohol|                 0.03500|
|      Coco-Glucoside|                 0.01500|
+--------------------+------------------------+
only showing top 10 rows

In [25]:
size_converted = spark.sql("""
    SELECT product_id, product_name, brand_name, oz_value AS size_oz, mL_value AS size_mL
    FROM separated_sizes
""")
size_converted.createOrReplaceTempView("size_converted")
size_converted.show(5)

+----------+--------------------+----------+-------+-------+
|product_id|        product_name|brand_name|size_oz|size_mL|
+----------+--------------------+----------+-------+-------+
|   P473668|La Habana Eau de ...|     19-69|    3.4|    100|
|   P473662|Rainbow Bar Eau d...|     19-69|    3.4|    100|
|   P473660|Kasbah Eau de Parfum|     19-69|    3.4|    100|
|   P473658|Purple Haze Eau d...|     19-69|    3.4|    100|
|   P473661|Kasbah Eau de Par...|     19-69|   0.25|    7.5|
+----------+--------------------+----------+-------+-------+
only showing top 5 rows

In [26]:
product_ingredients = spark.sql("""
    SELECT 
        p.product_id,
        TRIM(p.ingredient) AS ingredient,
        s.size_oz,
        s.size_mL
    FROM (
        SELECT 
            product_id, 
            EXPLODE(SPLIT(ingredients, ', ')) AS ingredient
        FROM product_df
    ) p
    JOIN size_converted s ON p.product_id = s.product_id
""")
product_ingredients.createOrReplaceTempView("product_ingredients")
product_ingredients.show(5)

+----------+--------------------+-------+-------+
|product_id|          ingredient|size_oz|size_mL|
+----------+--------------------+-------+-------+
|   P473668|         Linalool.']|    3.4|    100|
|   P473668|Alpha-Isomethyl I...|    3.4|    100|
|   P473668|             Eugenol|    3.4|    100|
|   P473668|   Coumarin Limonene|    3.4|    100|
|   P473668|              Citral|    3.4|    100|
+----------+--------------------+-------+-------+
only showing top 5 rows

In [27]:
matching_products_conc = spark.sql("""
    SELECT 
        pi.product_id,
        SUM(COALESCE(ic.standard_conc_percentage, 0) * pi.size_oz) AS total_concentration
    FROM product_ingredients pi
    LEFT JOIN ingredient_concentrations ic
    ON TRIM(pi.ingredient) = TRIM(ic.ingredient)
    GROUP BY pi.product_id
""")

matching_products_conc.createOrReplaceTempView("matching_products_conc")
matching_products_conc.show(10)

+----------+-------------------+
|product_id|total_concentration|
+----------+-------------------+
|   P455325|            0.04185|
|   P505023|0.36749999999999994|
|   P474304| 0.6628179999999999|
|   P471226|             0.1328|
|   P126301|0.24889999999999998|
|   P500098|             0.6175|
|     P4489| 2.2633799999999997|
|   P427731|0.07300000000000001|
|   P464238|            0.35445|
|   P503693|0.12336999999999998|
+----------+-------------------+
only showing top 10 rows

In [28]:
min_max_matching_conc = spark.sql("""
    SELECT 
        MIN(total_concentration) AS min_concentration,
        MAX(total_concentration) AS max_concentration
    FROM matching_products_conc
""")

min_max_matching_conc.show()

+-----------------+-----------------+
|min_concentration|max_concentration|
+-----------------+-----------------+
|              0.0|             39.2|
+-----------------+-----------------+

In [29]:
median_matching_conc = spark.sql("""
    SELECT 
        PERCENTILE_APPROX(total_concentration, 0.5) AS median_concentration
    FROM matching_products_conc
""")

median_matching_conc.show()

+--------------------+
|median_concentration|
+--------------------+
|               0.075|
+--------------------+

In [30]:
# Target definition: 0 being product_id below median matched concentration (<= 0.075), and 1 being product_id above matched concentration(> 0.075)

target_definition = spark.sql("""
    SELECT 
        mpc.product_id,
        mpc.total_concentration,
        CASE 
            WHEN mpc.total_concentration <= 0.075 THEN 0
            ELSE 1
        END AS target,
        tr.author_id,
        tr.product_name,
        tr.brand_name,
        tr.submission_time,
        tr.rating
    FROM matching_products_conc mpc
    LEFT JOIN total_reviews_df tr 
    ON mpc.product_id = tr.product_id
""")

target_definition.createOrReplaceTempView("target_definition")
target_definition.show(10)

+----------+-------------------+------+-----------+--------------------+----------+---------------+------+
|product_id|total_concentration|target|  author_id|        product_name|brand_name|submission_time|rating|
+----------+-------------------+------+-----------+--------------------+----------+---------------+------+
|   P126301|0.24889999999999998|     1| 5798933243|Take The Day Off ...|  CLINIQUE|     2023-03-20|     5|
|   P126301|0.24889999999999998|     1|25526458589|Take The Day Off ...|  CLINIQUE|     2023-03-10|     5|
|   P126301|0.24889999999999998|     1|12958904843|Take The Day Off ...|  CLINIQUE|     2023-02-26|     1|
|   P126301|0.24889999999999998|     1| 1316510353|Take The Day Off ...|  CLINIQUE|     2023-02-26|     4|
|   P126301|0.24889999999999998|     1| 8389515459|Take The Day Off ...|  CLINIQUE|     2023-02-26|     5|
|   P126301|0.24889999999999998|     1| 2427406909|Take The Day Off ...|  CLINIQUE|     2023-02-25|     5|
|   P126301|0.24889999999999998|     1| 7604128862|Take The Day Off ...|  CLINIQUE|     2023-02-24|     5|
|   P126301|0.24889999999999998|     1|39687587740|Take The Day Off ...|  CLINIQUE|     2023-02-23|     5|
|   P126301|0.24889999999999998|     1|22303444455|Take The Day Off ...|  CLINIQUE|     2023-02-22|     5|
|   P126301|0.24889999999999998|     1| 5473210775|Take The Day Off ...|  CLINIQUE|     2023-02-17|     5|
+----------+-------------------+------+-----------+--------------------+----------+---------------+------+
only showing top 10 rows

[Stage 100:=============> (50 + 4) / 54][Stage 101:>                (0 + 2) / 2]

In [31]:
# Compute correlation matrix for total_concentration from matching_products_conc & target from target_definition
correlation_matrix = spark.sql("""
    SELECT 
        corr(mpc.total_concentration, td.target) AS correlation
    FROM matching_products_conc mpc
    JOIN target_definition td 
    ON mpc.product_id = td.product_id
""")
correlation_matrix.show()

+------------------+
|       correlation|
+------------------+
|0.2825168745683915|
+------------------+

### **Model Design**  

 Using CatBoostClassifier (CatBoostAI’s GBDT framework), this model will classify and predict customers to target values of 0 or 1, with 1 being higher than median matching ingredient concentrations with P442990 and 0 being lower than median matching ingredient concentrations with P442990, and look into the likelihood of purchasing products with a higher than median matching ingredient concentration. The median temperature was taken as the boundary for high and low ingredient concentration match of P442990.

In [ ]:
# Load star schema tables for model input.
# fact_purchases provides all measures; dims supply categorical labels required by CatBoost.
_fact = pd.read_csv(f"{home_dir}/data/cleaned/btl_clean_{data_dt}_fact_purchases.csv")
_dp_labels = dim_product[['product_id', 'product_name']].rename(columns={'product_id': 'product_sk'})
_db_labels = dim_brand.rename(columns={'brand_id': 'brand_sk'})
_dt_labels = dim_time[['time_sk', 'submission_date']].rename(columns={'submission_date': 'submission_time'})

pdf_sabt = (
    _fact
    .merge(_dp_labels, on='product_sk', how='left')
    .merge(_db_labels, on='brand_sk', how='left')
    .merge(_dt_labels, on='time_sk', how='left')
    .rename(columns={'product_sk': 'product_id', 'author_sk': 'author_id'})
)
pdf_sabt.head()

In [33]:
# Check column names in data
pdf_sabt.columns

Index(['product_id', 'total_concentration', 'target', 'author_id',
       'product_name', 'brand_name', 'submission_time', 'rating'],
      dtype='str')

In [34]:
# Check summary statistics
pdf_sabt[['product_id', 'total_concentration', 'target', 'author_id',
       'product_name', 'brand_name', 'submission_time', 'rating']].describe().T

,count,mean,std,min,25%,50%,75%,max
total_concentration,976658.0,0.241731,0.506208,0.0,0.06275,0.1514,0.2856,39.2
target,981580.0,0.689947,0.462515,0.0,0.00000,1.0000,1.0000,1.0

In [35]:
pdf_sabt.groupby(['target'])[['total_concentration', 'rating']].describe().T

target                                 0              1
total_concentration count  304342.000000  672316.000000
                    mean        0.029172       0.337951
                    std         0.026689       0.584987
                    min         0.000000       0.075150
                    25%         0.000000       0.143500
                    50%         0.022270       0.226100
                    75%         0.055000       0.372000
                    max         0.075000      39.200000

In [36]:
data = pdf_sabt[['product_id', 'total_concentration', 'target', 'author_id',
       'product_name', 'brand_name', 'submission_time', 'rating']].copy()

In [37]:
# Separate target variable and features
from sklearn.model_selection import train_test_split

target_col = 'target'

X = data.loc[:, data.columns != target_col]
y = data.loc[:, target_col]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f'Training set size: {X_train.shape[0]} samples')
print(f'Testing set size: {X_test.shape[0]} samples')

Training set size: 785264 samples
Testing set size: 196316 samples

In [38]:
X_train.head()

,product_id,total_concentration,author_id,product_name,brand_name,submission_time,rating
322153,P375850,0.00000,2846809122,Facial Treatment Cleanser,SK-II,2021-06-01,5
525658,P429952,0.37575,1192882732,Jet Lag Mask,Summer Fridays,2020-01-20,5
578,P122774,0.03900,1529407678,All About Eyes Eye Cream,CLINIQUE,2012-08-15,4
34306,P427417,0.00750,11509663508,Niacinamide 10% + Zinc 1% Oil Control Serum,The Ordinary,2021-02-26,5
971911,P504595,0.20655,27594244118,Mini Rice Wash Skin-Softening Cleanser,Tatcha,2020-07-31,5

In [39]:
y_train.head()

322153    0
525658    1
578       0
34306     0
971911    1
Name: target, dtype: int32

In [40]:
print(y_train.value_counts())
print(y_test.value_counts())

target
1    541652
0    243612
Name: count, dtype: int64
target
1    135586
0     60730
Name: count, dtype: int64

In [ ]:
# Figure 3 -- Class Distribution (from actual y_train / y_test value counts)
import matplotlib.pyplot as plt
import numpy as np

train_counts = y_train.value_counts().sort_index()
test_counts  = y_test.value_counts().sort_index()
total_0 = train_counts[0] + test_counts[0]
total_1 = train_counts[1] + test_counts[1]
total   = total_0 + total_1

fig, axes = plt.subplots(1, 2, figsize=(11, 4))

labels = ["Class 0\n(Low Match)", "Class 1\n(High Match)"]
counts = [total_0, total_1]
pcts   = [c / total * 100 for c in counts]
colors = ["darkred", "darkblue"]
bars = axes[0].bar(labels, counts, color=colors, edgecolor="white", width=0.5)
for bar, pct, cnt in zip(bars, pcts, counts):
    axes[0].text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 8000,
                 f"{cnt:,}\n({pct:.1f}%)", ha="center", va="bottom", fontsize=10, fontweight="bold")
axes[0].set_title("Overall Class Distribution (n = {:,})".format(total), fontsize=11, fontweight="bold")
axes[0].set_ylabel("Record Count")
axes[0].set_ylim(0, total_1 * 1.2)
axes[0].yaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f"{int(x):,}"))
axes[0].grid(axis="y", alpha=0.3)

x = np.arange(2)
w = 0.35
c0_vals = [train_counts[0], test_counts[0]]
c1_vals = [train_counts[1], test_counts[1]]
axes[1].bar(x, c0_vals, w, label="Class 0 (Low Match)",  color="darkred",  edgecolor="white")
axes[1].bar(x, c1_vals, w, bottom=c0_vals, label="Class 1 (High Match)", color="darkblue", edgecolor="white")
axes[1].set_xticks(x)
axes[1].set_xticklabels(["Train (80%)", "Test (20%)"])
axes[1].set_title("Class Distribution by Split", fontsize=11, fontweight="bold")
axes[1].set_ylabel("Record Count")
axes[1].yaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f"{int(x):,}"))
axes[1].legend()
axes[1].grid(axis="y", alpha=0.3)

fig.suptitle("Figure 3 — Class Distribution", fontsize=13, fontweight="bold")
plt.tight_layout()
plt.savefig(f"{home_dir}/assets/fig3_class_distribution.png", dpi=150, bbox_inches="tight")
plt.show()

In [42]:
from catboost import CatBoostClassifier

# Categorical feature columns (string identifiers)
cat_features = ['product_id', 'author_id', 'product_name', 'brand_name', 'submission_time']

# Fill NaN in categorical columns with 'missing', then cast to str
for col in cat_features:
    X_train[col] = X_train[col].fillna('missing').astype(str)
    X_test[col]  = X_test[col].fillna('missing').astype(str)

# Fill NaN in numeric columns with 0 (total_concentration and rating)
for col in ['total_concentration', 'rating']:
    if col in X_train.columns:
        X_train[col] = pd.to_numeric(X_train[col], errors='coerce').fillna(0)
        X_test[col]  = pd.to_numeric(X_test[col],  errors='coerce').fillna(0)

model = CatBoostClassifier(iterations=500, depth=6, learning_rate=0.1, verbose=50, eval_metric='F1')
model.fit(X_train, y_train, cat_features=cat_features, eval_set=(X_test, y_test), plot=True)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

0:	learn: 0.9995013	test: 0.9997418	best: 0.9997418 (0)	total: 252ms	remaining: 2m 5s

50:	learn: 0.9999086	test: 0.9999078	best: 0.9999078 (3)	total: 6.38s	remaining: 56.2s

100:	learn: 0.9999086	test: 0.9999078	best: 0.9999078 (3)	total: 12.7s	remaining: 50s

150:	learn: 0.9999086	test: 0.9999078	best: 0.9999078 (3)	total: 18.3s	remaining: 42.2s

200:	learn: 0.9999086	test: 0.9999078	best: 0.9999078 (3)	total: 22.8s	remaining: 34s

250:	learn: 0.9999086	test: 0.9999078	best: 0.9999078 (3)	total: 25.8s	remaining: 25.6s

300:	learn: 0.9999086	test: 0.9999078	best: 0.9999078 (3)	total: 28.7s	remaining: 19s

350:	learn: 0.9999086	test: 0.9999078	best: 0.9999078 (3)	total: 31.6s	remaining: 13.4s

400:	learn: 0.9999086	test: 0.9999078	best: 0.9999078 (3)	total: 34.5s	remaining: 8.53s

450:	learn: 0.9999086	test: 0.9999078	best: 0.9999078 (3)	total: 37.4s	remaining: 4.07s

499:	learn: 0.9999086	test: 0.9999078	best: 0.9999078 (3)	total: 40.3s	remaining: 0us

bestTest = 0.9999077991
bestIteration = 3

Shrink model to first 4 iterations.

CatBoostClassifier(depth=6, eval_metric='F1', iterations=500, learning_rate=0.1, verbose=50)

In [43]:
# Figure 4 -- CatBoost Learning Curves from catboost_info TSV files
import pandas as pd
import matplotlib.pyplot as plt

learn = pd.read_csv("catboost_info/learn_error.tsv", sep="\t")
test  = pd.read_csv("catboost_info/test_error.tsv",  sep="\t")

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

axes[0].plot(learn["iter"], learn["F1"], label="Train F1", color="#2980B9", linewidth=1.5)
axes[0].plot(test["iter"],  test["F1"],  label="Test F1",  color="#E74C3C", linewidth=1.5, linestyle="--")
axes[0].set_title("F1 Score over 500 Iterations", fontsize=11, fontweight="bold")
axes[0].set_xlabel("Iteration")
axes[0].set_ylabel("F1 Score")
axes[0].legend()
axes[0].grid(True, alpha=0.3)
axes[0].set_ylim(0.88, 1.005)

axes[1].plot(learn["iter"], learn["Logloss"], label="Train Logloss", color="#2980B9", linewidth=1.5)
axes[1].plot(test["iter"],  test["Logloss"],  label="Test Logloss",  color="#E74C3C", linewidth=1.5, linestyle="--")
axes[1].set_title("Log Loss over 500 Iterations", fontsize=11, fontweight="bold")
axes[1].set_xlabel("Iteration")
axes[1].set_ylabel("Log Loss")
axes[1].legend()
axes[1].grid(True, alpha=0.3)

fig.suptitle("Figure 4 — CatBoost Learning Curves", fontsize=13, fontweight="bold")
plt.tight_layout()
plt.savefig(f"{home_dir}/assets/fig4_catboost_learning_curves.png", dpi=150, bbox_inches="tight")
plt.show()

/var/folders/qd/bdj1245s6yjgfq0g9fxz8n4m0000gn/T/ipykernel_82775/3793737516.py:30: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [44]:
y_pred = model.predict(X_test)

print(f'Predictions: {y_pred[:50]}')

Predictions: [1 1 0 0 1 0 0 1 0 0 1 1 1 0 0 0 0 1 1 1 1 0 1 1 1 0 1 1 1 1 0 1 1 0 0 0 1
 0 1 1 0 1 1 1 1 1 1 1 1 1]

In [45]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report, f1_score
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

# Evaluate the model
print(f'Accuracy: {accuracy_score(y_test, y_pred):.4f}')
print(f'F1: {f1_score(y_test, y_pred):.4f}')
print(f'Precision: {precision_score(y_test, y_pred):.4f}')
print(f'Recall: {recall_score(y_test, y_pred):.4f}')

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

cm_train = confusion_matrix(y_test, y_pred)
print(cm_train)

fig, ax = plt.subplots(figsize=(6, 5))
cmd_train = ConfusionMatrixDisplay(cm_train)
cmd_train.plot(ax=ax)
ax.set_title("Figure 5 — Confusion Matrix", fontweight="bold")
plt.tight_layout()
plt.savefig(f"{home_dir}/assets/fig5_confusion_matrix.png", dpi=150, bbox_inches="tight")
plt.show()

Accuracy: 0.9999
F1: 0.9999
Precision: 1.0000
Recall: 0.9998

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     60730
           1       1.00      1.00      1.00    135586

    accuracy                           1.00    196316
   macro avg       1.00      1.00      1.00    196316
weighted avg       1.00      1.00      1.00    196316

[[ 60730      0]
 [    25 135561]]

/var/folders/qd/bdj1245s6yjgfq0g9fxz8n4m0000gn/T/ipykernel_82775/1911670202.py:24: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [46]:
# Set model name

prefix_name="matched-conc_P442990_purchases"

model_name = f"btl_model_{get_datetime()}_{prefix_name}"
print(f"{model_name}")

20260419_1203
btl_model_20260419_1203_matched-conc_P442990_purchases

In [47]:
# Save model to models/ directory
import dill

os.makedirs(f"{home_dir}/models", exist_ok=True)
model_path = f"{home_dir}/models/{model_name}.pkl"

with open(model_path, "wb") as file:
    dill.dump(model, file)

print(f"Model saved as {model_path}")

Model saved as /Users/gyalm/Desktop/btl_model/btl_model/models/btl_model_20260419_1203_matched-conc_P442990_purchases.pkl